### ISSUE TITLE
Consider removing generic parameterization on Terminal and Frame

### ISSUE THREAD

**Issue by deontologician** [fdehau/tui-rs#107]
So currently, I have a bunch of declarations at the top of my rendering module that look like this:

```rust
type StdOut = termion::raw::RawTerminal<std::io::Stdout>;
type Backend = tui::backend::TermionBackend<StdOut>;
type Frame<'a> = tui::terminal::Frame<'a, Backend>;
type Terminal = tui::Terminal<Backend>;
```

Basically, it seems like the library is over-genericized a bit. Usually, I think adding a generic parameter when it can statically prevent issues the user might encounter. For the case of terminals, it seems like I'm unlikely to instantiate two `Terminal`s each with different backends and then get them confused. (I mean, it's possible, but not probably common).

The downside of course is that we need to keep track of all of this stuff. If it's all done within a function boundary, then type inference lets us skip the boilerplate, but if you want to pass a `Terminal` to a function, etc, you either have to specify it all out, or pass the buck and genericize your function.

Would it be possible to remove some of the generic parameters on the user-facing types like `Frame` and `Terminal`? I realize this is kind of a large task, but it'd significantly improve the ergonomics of the library in my opinion.

**Comment by fdehau** [comment]
I understand the issue but I'm not sure how to provide a simpler interface. One solution would be to have mutually exclusive feature flags and use the only backend available to construct the `Terminal` and by extension the `Frame`. But then the backend initialization is not exposed to the end user and the you either make a choice to instantiate the solution that fit all needs (think `AlternateScreen<MouseTerminal<RawTerminal<Stdout>>>` for the termion case) or configure it using something like a `HashMap` of options that you are not guaranteed to be able to enforce depending on the chosen backend. I would argue that the current solution force the end user to select a backend that fit their needs and learn about what is supported.

Therefore, I'm not opposed to the idea but I think that we need more feedback.

**Comment by fdehau** [comment]
Closing as I haven't had any similar feedback and it does not appear to be a blocking point for most end users.
