### ISSUE TITLE
Question: How to understand some constants in the canvas module?

### ISSUE THREAD

**Issue by longwusha** [fdehau/tui-rs#115]
Many predefined constants are used in the canvas module, for example:

```rust
pub const DOTS: [[u16; 2]; 4] = [
    [0x0001, 0x0008],
    [0x0002, 0x0010],
    [0x0004, 0x0020],
    [0x0040, 0x0080],
];
pub const BRAILLE_OFFSET: u16 = 0x2800;
```

What do these constants mean, how do you get these values, and what effect do they have on the rendering results?

**Comment by fdehau** [comment]
Closing in favor of #114 for the explanation.
