### ISSUE TITLE
Question: How to customize the coordinate system of the canvas?

### ISSUE THREAD

**Issue by meteor-lsw** [fdehau/tui-rs#117]
Now the default coordinate system of the canvas is to set the origin in the center of the screen, the positive direction of the x-axis is to the right, and the positive direction of the y-axis is upward. If I want to change the origin to the top left corner of the screen, the positive x-axis is to the right and the y-axis is down, what should I do?

**Comment by fdehau** [comment]
There is no way at the moment to do such things. I would welcome a PR though =).

**Comment by vdods** [comment]
Maybe related: https://github.com/fdehau/tui-rs/discussions/608
