### ISSUE TITLE
More than one modifier on a style

### ISSUE THREAD

**Issue by deifactor** [fdehau/tui-rs#122]
As the title says. Right now there's no way to make text that's (for example) both bold *and* italic. So either the `modifier` field on `Style` should be a set/vec/whatever or `Modifier` itself should be able to contain more than one individual modifier.

**Comment by fdehau** [comment]
That is a good suggestion. I'm not sure whether a bit flag or a small set implementation would be preferable though. I'll look into it...

**Comment by deifactor** [comment]
I think it'd be nice to have whichever's easier, and then benchmarking can come later.
