### ISSUE TITLE
Paragraph scroll uses high cpu

### ISSUE THREAD

**Issue by swalladge** [fdehau/tui-rs#124]
I noticed that scrolling a Paragraph widget (eg. setting scroll to += 1 in a loop controlled by user input) is really slow and uses a lot of cpu power. Not sure whether this is a bug or a known limitation of the widget.

If the latter, does anyone know where I might start to have paged content displaying from a cli rust app? I thought about launching `less` as a child process, but ran into problems with corrupted terminal...

**Comment by fdehau** [comment]
What version are you using and could you check if you were testing this behavior using a debug or a release build ?

**Comment by swalladge** [comment]
Version 0.3.0. I see this behaviour in both the debug and release builds.

For reference, this is how I'm using it: https://github.com/swalladge/wallabag-rs/commit/07b63ec06023b18b734328943685af5891863e77#diff-662b6f9f144212397eb884431c5a21cb

**Comment by fdehau** [comment]
Couldn't this be because html2text is called every time you draw ? Have you been able to profile your application ?

**Comment by swalladge** [comment]
Lol how did I miss that. Yes, that was exactly the issue :man_facepalming: Thanks.
