### ISSUE TITLE
Margin property configurable for Paragraph widget

### ISSUE THREAD

**Issue by rruizt** [fdehau/tui-rs#136]
Right now, applications that use the Paragraph widget cannot customize the margin between the text and the border of the widget.

The idea would be to add a property that works in a similar way of how the Layout margin property does.

**Comment by fdehau** [comment]
While I see how this can be useful, have you thought about using a Layout call for this purpose ? Given an `area1` to draw to, you could draw a `Block` on `area1` and then use a `Layout` call on `aera1` too with the chosen margin which will give you an `area2` to draw a `Paragraph` without a block. This should achieve the expected output if I'm not mistaken (as illustrated in the [block example](./examples/block.rs))

**Comment by rruizt** [comment]
Indeed, that worked perfectly fine.

I used to have an internal block for the Paragraph where I wold set the title, but setting the title in the outer block and then defining the paragraph inside of the layout made the trick. 

Just putting it here as an example of the workaround:

```rust        
Block::default()
        .borders(Borders::ALL)
        .title_style(Style::default().modifier(Modifier::BOLD)).title(&title)
        .style(Style::default().bg(Color::Black))
       .render(&mut f, size);
            
let chunks = Layout::default()
      .direction(Direction::Horizontal)
      .margin(3)
      .constraints([Constraint::Percentage(100)].as_ref())
      .split(size);

Paragraph::new(text_complete.iter())
      .wrap(true)
      .scroll(current_scroll)
      .render(&mut f, chunks[0]);
```

Thank you for your work!
