### ISSUE TITLE
Feature request: Have more control over the colors of each canvas cell

### ISSUE THREAD

**Issue by longwusha** [fdehau/tui-rs#142]
@fdehau  As you mentioned in #114 . 

I think we need to do some refactoring on Shape so that we can control the color of each point, which makes it easier to use. Now a Shape can only use one color, which makes us limited in developing some complex rendering effects, and has some adverse effects on rendering performance.

> In any way, I'm afraid that you cannot achieve what you want with the current state of the crate and that some changes are required on the library side.I would maybe start by modifying the `Shape` trait to take a `Style` struct along the coordinates so that you can have more control over the colors of each cell.

**Comment by fdehau** [comment]
Yeah, reading my previous comment again, I think I was a bit overconfident about the possibility of controlling the color of each point within the braille pattern. My first thought would be that the color is set from the entire cell as the terminal is changing the color of all the unicode characters following the ansi escape code changing the color. However, the order in which those ansi escape code are issued might allow better control over the colors of each point. This would require further research while I'm not sure that changing all the rendering logic for this particular problem would worth it.

**Comment by fdehau** [comment]
I believe this has been added in #237
