### ISSUE TITLE
How to fill gauges in a vertical way rather than the default (horizontal)

### ISSUE THREAD

**Issue by im7FFY** [fdehau/tui-rs#158]
Is there a way to fill gauges in a vertical way ?
I checked a lot on crate docs of tui and for this particular widget but did not found a way to do it. Is it an error of my part or is this feature not present?

**Comment by fdehau** [comment]
That's not possible at the moment but it shouldn't be that hard to add to the current Gauge widget, i.e some kind of "orientation" option and an update in the rendering logic to take this into account.
