### ISSUE TITLE
Text should implement Eq

### ISSUE THREAD

**Issue by DarrienG** [fdehau/tui-rs#162]
We were sort of discussing this here at #155 

I've finally gotten to writing tests for [a project](https://gitlab.com/DarrienG/terminal-typeracer) I'm working on right now and comparing the colors styles as well as the text in the text enum would be really handy.

**Comment by DarrienG** [comment]
Update: Making structs with Text types is also a bit of a nuisance because they can't implement Debug, which means I end up adding custom to_string() methods for structs with Text fields.

**Comment by fdehau** [comment]
I'm still not sure about the use case there. Since your project is public could you point me to some code that might be improved if that was the case ?

**Comment by DarrienG** [comment]
Sure. My project is a terminal game that mimics typeracer.com You can see a short example here if you'd like: https://asciinema.org/a/hEcf1pD2v60wUxiSIHdFWs5zN

Unlike most terminal programs where coloring is an enhancement, the bulk of the game revolves around properly coloring terminal output so the user knows when there's an error.

Most of the logic that makes it happen is in a method here: https://gitlab.com/DarrienG/terminal-typeracer/blob/master/src/game/mod.rs#L103 which while isn't too complicated, it hairy enough that it should definitely have a few tests. It's output ends up being a set of formatted texts.

A few good tests would reassure users and contributors (and myself) that they aren't breaking anything if they mess with the code.

You can compare RGB objects [with Termion](https://github.com/redox-os/termion/blob/master/src/color.rs#L154) but I'd rather not lock myself into a backend if I can help it.

Side note: I think PartialEq might be good enough. It's worth noting I'm still pretty new to rust, so I'm not fully aware of all of the differences and intricacies.

**Comment by fdehau** [comment]
Alright I get it now =). I just added PartialEq to Text in master. Let me know if that helps you write your tests.

**Comment by DarrienG** [comment]
Thanks so much :)

**Comment by DarrienG** [comment]
This works great! Thank you!

**Comment by DarrienG** [comment]
We're looking to release the binary on crates.io, but are still reliant on pulling from HEAD for partialEq for tests. Do you think you could make a release for this?

**Comment by fdehau** [comment]
I've made this change available in v0.6.2. Sorry, I should have released this sooner =)

**Comment by DarrienG** [comment]
No worries, thanks a bunch!
