### ISSUE TITLE
arm raspbery pi error

### ISSUE THREAD

**Issue by letarg0** [fdehau/tui-rs#168]
cargo build
warning: unused manifest key: badges.appveyor.repository
warning: unused manifest key: badges.travis-ci.repository
warning: unused manifest key: example.required-features
warning: unused manifest key: example.required-features
warning: unused manifest key: example.required-features
warning: unused manifest key: example.required-features
warning: unused manifest key: package.autoexamples
warning: unused manifest key: package.edition
   Compiling tui v0.6.1 (file:///home/user/tui-rs)
error: found invalid character; only `#` is allowed in raw string delimitation: t
   --> src/backend/termion.rs:131:24
    |
131 |         let terminal = r#try!(termion::terminal_size());
    |                        ^^

error: aborting due to previous error

error: Could not compile `tui`.

To learn more, run the command again with --verbose.

**Comment by letarg0** [comment]
rustc --version
rustc 1.24.1 (f2dda7fd7 2018-08-16)

**Comment by fdehau** [comment]
I've replaced the try call with the new "?" syntax. You may try to compile again with master to see if that fix the issue.
