### ISSUE TITLE
Showcase: spotify-tui

### ISSUE THREAD

**Issue by Rigellute** [fdehau/tui-rs#184]
Thank you for making this wonderful crate!

I've used it to make at TUI for Spotify.

Linking here in case this can be used for demonstration purposes for others - https://github.com/Rigellute/spotify-tui

**Comment by fdehau** [comment]
That's a very cool project :+1:. I'll be sure to linked it from the README as it might help a lot of people get a sense of how this crate can be used in a complex application. If you have any feedback, especially on things you've found challenging or obscure it would be greatly appreciated =).
