### ISSUE TITLE
It is not possible to suspend/activate raw mode on termion backend wrapped by TUI

### ISSUE THREAD

**Issue by kuznero** [fdehau/tui-rs#187]
`TermionBackend` does not expose these primitives. It would be great to have it under user's control.

```rust
  let source = io::stdout();
  let stdout = source.into_raw_mode()?;
  let backend = TermionBackend::new(stdout);
  backend.suspend_raw_mode(); // should pass-through to termion crate
```

**Comment by sashaweiss** [comment]
Was there a reason this was closed? I'm having the same kind of issue, and would love to know if/how this was resolved.
