### ISSUE TITLE
What are the units of Rect in different parts of the code?

### ISSUE THREAD

**Issue by TotalKrill** [fdehau/tui-rs#190]
I am trying to dynamically control how many elements I can fit into a paragraph, I naively used the rect.height variable, assuming they were in characters, and thus If i had a Vec<RawText> I could use `.take(rect.height)` and then the entire paragraph would be filled exactly, not to many elements, and not to few. But this did not really work, it fills approximatly 1/3 of the paragraph using this way. Why is that?

**Comment by fdehau** [comment]
Closing this since I failed to answer you within a reasonable timeline. If you are still facing this issue, feel free to open a new issue (preferably using the extensive bug report template so that I have all the information required to help you).
