### ISSUE TITLE
`SelectableTable` - Feature Request

### ISSUE THREAD

**Issue by sputnick1124** [fdehau/tui-rs#196]
Recently in `spotify-tui`, we had a need to have a table which would automatically scroll to allow the highlighted item in the table always visible, similar to how `SelectableList` works. 

[This was implemented](https://github.com/Rigellute/spotify-tui/pull/135) for the use case within `spotify-tui`, but perhaps would be widely applicable to other users of `tui-rs`.

I'd love to get feedback from other users if this would be broadly useful. I could even take a shot at an implementation if so. Thanks!

[![asciicast](https://asciinema.org/a/FdKDHNjloi0CgFKXo7etLvYjE.svg)](https://asciinema.org/a/FdKDHNjloi0CgFKXo7etLvYjE)

**Comment by aryakaul** [comment]
Just wanted to drop a note saying that at least I would find the Widget helpful.

I'm currently trying to adapt your implementation to address the use case described in #200 -- really cool work!

**Comment by orhun** [comment]
It's a great idea, must be implemented. I'm using your snippet that handles the selection with an offset and `skip` function. Working well!

**Comment by fdehau** [comment]
I would be more than happy to have such feature in the library. I would also suggest to merge this functionality directly in the `Table` widget if possible (as it is my intent to merge `List` and `SelectableList`). PRs are welcome.

**Comment by sputnick1124** [comment]
Sounds good! I'll start putting some code together in the coming days when I get some down time over the holidays.

**Comment by sputnick1124** [comment]
Sorry this took me so long to get around to. I got seriously distracted by Advent of Code :blush:

**Comment by fdehau** [comment]
It has been implemented in #242 using the initial work of @sputnick1124.
