### ISSUE TITLE
Crossterm+Windows support

### ISSUE THREAD

**Issue by jonathandturner** [fdehau/tui-rs#199]
Would love to try using tui, but when I run the demo it looks like it's not quite ready to use in Windows. 

Here's running the crossterm_demo in Windows:

![image](https://user-images.githubusercontent.com/547158/68733170-b30c0280-063a-11ea-97e7-eb0521e16180.png)

Is there a better way to get Windows support aside from crossterm? If not, are there any plans for making Windows supported?

**Comment by wickie73** [comment]
You need to install the [FreeMono](https://fonts2u.com/free-monospaced.font) font.

Same as Javascript library [blessed-contrib](https://github.com/yaronn/blessed-contrib) you need to install the [FreeMono](https://fonts2u.com/free-monospaced.font) font descibed in [Running Terminal Dashboards on Windows](https://webservices20.blogspot.com/2015/04/running-terminal-dashboards-on-windows.html). 

After installing the font I could not use it with Windows cmd or powershell terminal. 
Instead I used [Cmder](https://cmder.net/) where you can used the FreeMono font. 

Then the crossterm demo looks like: 
![grafik](https://user-images.githubusercontent.com/17014518/69486134-e58eda00-0e48-11ea-9d2f-83d578e035f8.png)

**Comment by jonathandturner** [comment]
@wickie73 - that's not a good solution, as it requires adding more fonts to the user's terminal. Many of these console apps should be `cargo install`-able, and should have that kind of impact on the system.

Luckily the parts that aren't supported can be replaced by other glyphs that have broader support. This is just a request that we use glyph choices that are more crossplatform by default.

**Comment by wickie73** [comment]
@jonathandturner Thank you. You are right, console apps should be `cargo install`able. 
Do you have any idea, which kind of glyphs makes sense here?

**Comment by TimonPost** [comment]
This is more an issue of supportability, it is indeed a problem that windows lack support for certain symbols.

**Comment by fdehau** [comment]
I think that a path forward an increased portability of this library across OS is to support at least two sets of those glyphs. A basic set that is guaranteed to render correctly everywhere but doesn't look as nice as one might expect and an enhanced set that is nicer on the eyes but might require the user to patch fonts or a terminal emulator supporting modern features.

Therefore we might have to:
* define what this basic set of glyphs could look like (might be more problematic for some widgets).
* think about how this choice is exposed to consumers of this crate (a global switch, a switch per widget, etc...)

**Comment by fdehau** [comment]
@jonathandturner I've finally had the time to setup a full Windows environment to reproduce the issue. I think that I've found an acceptable solution in #264. It allows app developers to choose on a widget basis a restricted set of symbols that are better supported by an unmodified `cmd.exe`. The README and the demo shows how this can be put behind a command line flag or a config option to degrade the output quality in favor of a better portability. For reference those are screenshots before and after the enhanced graphics (i.e unusal unicode symbols  and braille patterns) were disabled:

Enhanced graphics enabled (not really supported by cmd.exe):
![tab1_before](https://user-images.githubusercontent.com/10096255/79173459-e4f6e000-7df7-11ea-93db-c498b593b532.PNG)
![tab2_before](https://user-images.githubusercontent.com/10096255/79173464-e6280d00-7df7-11ea-97a8-fc6bf8489179.png)

Enhanced graphics disabled (the result is not as fine grained as with a custom font but the weird symbols are gone):
![tab1_after](https://user-images.githubusercontent.com/10096255/79173465-e6280d00-7df7-11ea-93d5-fc1b82110e35.png)
![tab2_after](https://user-images.githubusercontent.com/10096255/79173462-e58f7680-7df7-11ea-9c02-c5c596bc5a16.png)

**Comment by jonathandturner** [comment]
@fdehau this is great news! I'm looking forward to working with it

**Comment by jonathandturner** [comment]
@fdehau do you know how the enhanced mode looks in the new Windows Terminal?

**Comment by fdehau** [comment]
@jonathandturner Those are the screenshots I get in the new Windows Terminal:

Without enhanced graphics:
![terminal_off](https://user-images.githubusercontent.com/10096255/79231787-e3b0cc00-7e66-11ea-8a78-d7be77bfbff5.png)

With enhanced graphics:
![terminal_on](https://user-images.githubusercontent.com/10096255/79231784-e3183580-7e66-11ea-94ef-a4970a120c51.png)

As you can see the braille patterns are supported (I assume because of the different default font, i.e Cascadia Code) so every widget based on `Canvas` work as expected (`Chart`, `Map`, etc..). However the block unicode symbols still seem a bit off in the `Sparkline` and `BarChart` widgets. Using only full and half blocks (first picture) gives a better result.

Since the set of symbols are set on a widget basis, an app developer could put those choices behind different flags (e.g something like `enable_braille_patterns`, `enable_detailed_blocks`).
