### ISSUE TITLE
bg() for styled text does not seem to do anything.

### ISSUE THREAD

**Issue by PorkSausages** [fdehau/tui-rs#201]
Styled text with bg color is not drawn with a bg color. Tested on Terminal.app, iTerm & VSCode terminal. Not sure if bug or intended use of bg hasn't been documented?

**Comment by fdehau** [comment]
I'm closing this since I'm not able to reproduce the issue. Feel free to reopen the issue (with all the required information, see the issue template for a bug report) if you still have a problem with this.
