### ISSUE TITLE
 Add Popup box

### ISSUE THREAD

**Issue by betta-cyber** [fdehau/tui-rs#211]
It would be nice to have a popup box widget or a dialog widget to show some message for user.

![alt image](https://camo.githubusercontent.com/1f2e44ca0074c3c5b06880cab3b2062595693d1c/68747470733a2f2f692e696d6775722e636f6d2f33596c656f7a632e706e67)

It could be like this. cursive have this widget. so i choose it for a example.

**Comment by fdehau** [comment]
closing because @extrawurst has shown in #251 how to implement this.

**Comment by dataO1** [comment]
I think it would still be great to have this in the standard toolbox of Widgets.
I needed to google and find this issue to know, that someone has already implemented this, I think having it on the github readme would be great!
