### ISSUE TITLE
Increase the threshold that causes chart legends to be hidden

### ISSUE THREAD

**Issue by ClementTsang** [fdehau/tui-rs#221]
**Is your feature request related to a problem? Please describe.**
I've been using tui-rs to work on [bottom](https://github.com/ClementTsang/bottom), and one of my  graphs is set to take up ~1/3 of the terminal height and ~1/2 the terminal width.  It's legend contains only 2 entries.  On full screen, it's fine - the chart label will show and all is good.  However, shrinking to half width or half height seems to prove to be too much and will hide the legend, despite plenty of room remaining.

**Describe the solution you'd like**
Unless there's a reason I'm missing, I think it would be nice to increase the threshold that triggers legends to not be drawn.  In `chart.rs` I see that you're currently setting the threshold to be 1/3 of the graph's layout.  Would it be possible to increase it?  1/2 or 2/3 would probably still work IMO.  I've used a fork of this project and set it to that and it seems fine, but I would personally prefer it if it was in the main project, or at least get an explanation to why it isn't possible to do so.

**Describe alternatives you've considered**
For some components I've just moved them out of the chart into their own sections.  In most cases, this is fine - for example, with CPU displays, it makes more sense to put them as their own separate table of entries, since high core count CPUs are more common and cramming 16+ legend entries into a chart is a bad idea.

However, in my earlier case, it just makes little sense to allocate an entire table chunk just for 2 measily entries, especially when the graph has plenty of room.

**Additional context**
Here's an example of full screen (working fine):

![image](https://user-images.githubusercontent.com/34804052/72401880-58b31f00-371b-11ea-99dd-76238041b5bb.png)

Half width hides it already:
![image](https://user-images.githubusercontent.com/34804052/72401888-6072c380-371b-11ea-9561-82ccfa398a46.png)

Thanks!

**Comment by fdehau** [comment]
Thanks for the detailed request. That's a very cool looking project =). I think I may have found a way to let you have more control over this behavior with this PR #224. Let me know what you think.

**Comment by ClementTsang** [comment]
Nice!  Looks just like what I need.

**Comment by fdehau** [comment]
fixed in #224
