### ISSUE TITLE
Make Style::* functions `const`

### ISSUE THREAD

**Issue by MalteT** [fdehau/tui-rs#223]
**Is your feature request related to a problem? Please describe.**
I would like to declare `const`ants for a few styles, which could then be used everywhere easily.
```rust
    const SOME_STYLE: Style = Style::new()
        .fg(Color::Red)
        .bg(Color::Blue)
        .modifier(Modifier::DIM);
```
Currently I have to utilize the lazy_static crate for that.

**Describe the solution you'd like**
Adding `const` to:
- `Style::fg`
- `Style::bg`
- `Style::modifier`
and adding a `pub const fn new() -> Self` which does the same as `Style::default` would allow that.

**Describe alternatives you've considered**
[lazy_static](https://crates.io/crates/lazy_static), which is unnecessary overhead.

I already tested my solution and could assemble a PR..

**Comment by fdehau** [comment]
That's a very reasonable idea. Waiting for the PR ;)
