### ISSUE TITLE
Add a table to show differences between different backends

### ISSUE THREAD

**Issue by nicoxxl** [fdehau/tui-rs#227]
**Is your feature request related to a problem? Please describe.**
In the README, there is only a list of the differents backends.

**Describe the solution you'd like**
I would be nice to have a little bit of comparison between backends, like a table, to help chose which one to use when someone has no idea.

EDIT : Forgot to fill the body of the issue

**Comment by teohhanhui** [comment]
> It supports all UNIX and Windows terminals
>
> https://github.com/crossterm-rs/crossterm/blob/b9c8dcdbfa39d6dbe14a73d30a89fea7883b4dcc/README.md

https://github.com/crossterm-rs/crossterm/blob/b9c8dcdbfa39d6dbe14a73d30a89fea7883b4dcc/.github/workflows/crossterm_test.yml#L19

Crossterm definitely supports MacOS.
