### ISSUE TITLE
Chart GraphType::Line / Canvas Line lines don't work with continuous data

### ISSUE THREAD

**Issue by tarkah** [fdehau/tui-rs#232]
**Describe the bug**
Using a dataset that has values to plot on every point of the x axis doesn't reliably generate lines. The current implementation requires there to be space along the x / y axis between x/y1 and x/y2 to plot the connecting points between.

A hack to get around this is to multiply the high end of your x_bounds by some factor like 100. And then also multiply the x point in the dataset by the same factor.

**To Reproduce**
- Plot 10 points with large variability in the y axis along x1, x2 .. x10 with x_bounds [0, 10].
- To fix, plot the same ten points along x10, x20 .. x100 with x_bounds [0,100].

**Expected behavior**
If Line Chart is an option given to users, they shouldn't have to modify their dataset to get it to plot a line.

I don't know if this "hack" should be applied under the hood / if the "scale" it uses should be a parameter, or if this should be highly documented.

**Screenshots**
Real world example in the app I'm building

Before:
![Screenshot from 2020-02-21 13-28-59](https://user-images.githubusercontent.com/10239377/75077463-b32c6180-54b7-11ea-896c-846e472c6580.png)

After:
![Screenshot from 2020-02-21 13-27-36](https://user-images.githubusercontent.com/10239377/75077471-b9bad900-54b7-11ea-845c-d79d773532dd.png)

Diff of my hack:
```diff
diff --git a/src/widget/stock.rs b/src/widget/stock.rs
index 83a169c..49a5c4b 100644
--- a/src/widget/stock.rs
+++ b/src/widget/stock.rs
@@ -12,6 +12,8 @@ use tui::widgets::{
     Axis, Block, Borders, Chart, Dataset, GraphType, Marker, Paragraph, Tabs, Text, Widget,
 };
 
+const X_SCALE: usize = 100;
+
 pub struct StockWidget {
     symbol: String,
     stock_service: service::stock::StockService,
@@ -117,7 +119,7 @@ impl StockWidget {
     fn x_bounds(&self) -> [f64; 2] {
         match self.time_frame {
             TimeFrame::Day1 => [0.0, 1000.0], // Need to update once intra ready
-            _ => [0.0, (self.prices.len() + 1) as f64],
+            _ => [0.0, ((self.prices.len() * X_SCALE) + 1) as f64],
         }
     }
 
@@ -282,7 +284,7 @@ impl Widget for StockWidget {
 }
 
 fn cast_as_dataset(input: (usize, &f32)) -> (f64, f64) {
-    ((input.0 + 1) as f64, *input.1 as f64)
+    (((input.0 * X_SCALE) + 1) as f64, *input.1 as f64)
 }
 
 fn cast_historical_as_price(input: &HistoricalDay) -> f32 {
```

**Desktop (please complete the following information):**
N/A

**Comment by fdehau** [comment]
It might have already been solved by #217. Not yet released though.

**Comment by fdehau** [comment]
Now that I'm reading this again, are you reporting a bug for the current master ? If so could you report the commit you are testing with ?

**Comment by tarkah** [comment]
That's actually the commit I'm using. I'm using the new GraphType::Line from this. However, I noticed the same issues when using Canvas directly with Line.

The way a line is drawn between x,y1 and x,y2 requires there's actual points between to plot the line on. Points (x,y) (1,1) to (2,1) won't draw a straight line because there is no room between 1 and 2 to plot anything.

I wouldn't necessarily say this is a "bug", but it feels weird having to modify my underlying data to get the line to display.

**Comment by fdehau** [comment]
I've took some time to review the existing code and came to the conclusion that the current approach was not very good for that kind of use cases (especially the fact that there is no control over the "resolution" of the drawn objects). Thus I've opened a new PR that changes quite a lot of things regarding how shapes are drawn to the canvas, including a new line drawing algorithm here #237. I still need to polish the PR but I think that's a good start. The noticeable improvement is that you should not have to modify your data anymore.

**Comment by tarkah** [comment]
This is great, thank you! I'll give the PR a test and let you know how it works.

**Comment by tarkah** [comment]
So I'm trying to test this out, but I am getting majorly tripped up by the changes in master on the Widget trait. Converting from `draw(&mut self` to `render(self`... why isn't render taking `&self`? The `self` requirement currently breaks my app completely. What am I missing?

**Comment by tarkah** [comment]
Ahh, I missed the StatefulWidget change. Hmmm... So basically my current struct which implements Widget becomes the State of a new struct which just basically keeps the old draw function for implementing Stateful widget.

**Comment by tarkah** [comment]
Got it moved over, it wasn't too painful!

And it works! Here is the before (without manual scaling fix) and after, using the PR (without manual scaling). It now basically looks like it did when I was manually fixing my dataset.

![Screenshot from 2020-03-06 12-47-37](https://user-images.githubusercontent.com/10239377/76121641-ffdc6600-5fa8-11ea-9d17-1ce76b6ab311.png)

![Screenshot from 2020-03-06 12-46-47](https://user-images.githubusercontent.com/10239377/76121642-0074fc80-5fa9-11ea-9cc9-f7a45100bb96.png)
