### ISSUE TITLE
Upstream Crossterm bug in 0.16.0

### ISSUE THREAD

**Issue by tarkah** [fdehau/tui-rs#240]
Wanted to get this on your radar to make sure a patched release of crossterm is used before the next release on tui-rs. There is a file descriptor leak affecting 0.16.0, which was recently updated in master. I c an confirm I experience this issue when using master today.

It has been patched already, see https://github.com/crossterm-rs/crossterm/pull/383, but there is no new release yet.

**Comment by fdehau** [comment]
Thanks for the heads up. I've just updated the crossterm dependency to point on the current master instead so that people do not experience the same issue. This will also prevent me from publishing without updating the crossterm version again.

**Comment by extrawurst** [comment]
@fdehau can be closed, right? How about a release? `0.9` or point release?

**Comment by fdehau** [comment]
@extrawurst Yes and regarding the release, I should be able to do it this week but I'm performing some manual tests on Windows first =).
