### ISSUE TITLE
Add a 'swap_buffers' to terminal::Terminal?

### ISSUE THREAD

**Issue by lesurp** [fdehau/tui-rs#247]
**Is your feature request related to a problem? Please describe.**
After looking at the implementation of `terminal.draw(..)` I realize that, if we had a way to swap the buffers, it would be possible to reproduce the exact behaviour of `terminal.draw(...)` without the need for a closure, which, at least in my case, could make my code cleaner.

**Describe the solution you'd like**
```rust
    pub fn swap_buffers(&mut self) {
        self.buffers[1 - self.current].reset();
        self.current = 1 - self.current;
    }
```

**Comment by fdehau** [comment]
You haven't explained how this will make your code cleaner.
