### ISSUE TITLE
crossterm (re)size broken

### ISSUE THREAD

**Issue by extrawurst** [fdehau/tui-rs#250]
**Describe the bug**
In order to prepare the pull request for the Clear-feature (https://github.com/fdehau/tui-rs/pull/244) I pulled in the master and realized that crossterm terminal sizing seems broken: (see screenshot)

The terminal seems to have a default size and not using up the actual terminal size.
Also the resize events are not changing anything.

**To Reproduce**
In my case (macOS) I only need to run the Crossterm-demo:
```
cargo run --example crossterm_demo --no-default-features --features="crossterm" --release -- -tick-rate 200
```
**Expected behavior**

**Screenshots**
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/776816/77248557-a330aa80-6c3a-11ea-8355-235801631b14.png">

**Desktop (please complete the following information):**
 - OS: macos
 - Terminal Emulator: iTerm2
 - Crate version: master
 - Backend: crossterm

**Additional context**
This was working as intended in the previous release

**Comment by heyrict** [comment]
Well, afaik the resize event should be handled manually in `tui-rs`. Sending resize events from `crossterm` backend by adding [these lines](https://github.com/heyrict/exhaust/blob/master/src/event.rs#L94-L98) to your event.rs should fix the issue.

**Comment by extrawurst** [comment]
@heyrict "your events.rs"? as I said I am referring to the `official` demo from this repo. shouldn't this sort of thing be done in there if that's necessary? ;)

**Comment by heyrict** [comment]
@extrawurst Got it :ok_hand:

**Comment by extrawurst** [comment]
I quickly reiterate the findings based on #252 (see https://github.com/fdehau/tui-rs/pull/252#issuecomment-603761675)

The problem seems to be the fact that `tui-rs` does not specify any version for the Crossterm dependency: something seems to be broken when building with crossterm version `>=0.16`

**Comment by extrawurst** [comment]
I now tried to build against the recent crossterm `0.17` and now the whole demo crashes:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Other, error: "Failed to initialize input reader" })', examples/crossterm_demo.rs:54:16
```
🙈

**Comment by heyrict** [comment]
Oh, my fault. I've just run the crossterm demo on the master branch, and found resizing just works.

It seems that the crossterm demo **will implicitly send a tick event** when resize in L54, and I've closed the PR as there is no need to add an explicit one.

> ... and now the whole demo crashes:

What if you handle the `Result` correctly?

**Comment by extrawurst** [comment]
Nope handling the Result means no input event is arrives anymore, this seems to be a separate issue/regression with crossterm release `0.17` though.

trying all commits from there It is also obvious that this is the commit that broke the *resizing*
https://github.com/crossterm-rs/crossterm/commit/52b9d479c16fed8208449cb0ab9c59823a858f0c

which means that for now the safest way is to pin crossterm for everyone to `0.16.0`:
```
crossterm = { version="0.16.0", optional = true }
```

everything went south from there - `0.16.1` introduced the resizing issue - `0.17` breaks the whole input.

**Comment by extrawurst** [comment]
some update: the input issue on crossterm was fixed (https://github.com/crossterm-rs/crossterm/issues/404), now we are back to **just** having the resize issue

**Comment by extrawurst** [comment]
I can confirm that the resizing issue itself is also a regression in crossterm: https://github.com/crossterm-rs/crossterm/issues/406

**Comment by extrawurst** [comment]
crossterm `0.17.3` fixes the resize/size issue and a PR to upgrade to that version is open: #262
