### ISSUE TITLE
Style items individually in `SelectableList`

### ISSUE THREAD

**Issue by ellishg** [fdehau/tui-rs#254]
**Is your feature request related to a problem? Please describe.**
I would like items in `SelectableList` to be styled individually like they are in `List`.

**Describe the solution you'd like**
`List::item` takes as input an iterator to `Text`, but `SelectableList::item` takes a slice of `str`. It would be nice if these were consistent. 

**Describe alternatives you've considered**
I could use `List` and add my own code to make it selectable.

**Additional context**

**Comment by fdehau** [comment]
`SelectableList` functionality has been merged back in `List` on the current master (you can check the [changelog](https://github.com/fdehau/tui-rs/blob/master/CHANGELOG.md) for further details). This change will be in the upcoming 0.9 release.
