### ISSUE TITLE
Write control characters in a `RawText` widget

### ISSUE THREAD

**Issue by DevinR528** [fdehau/tui-rs#256]
I am working on a `tui` powered [matrix-client](https://github.com/DevinR528/RumaTui) and so far it's working great! I have recently run into the issue of rendering markdown for messages. I am hopping to be able to have a widget that acts like `Paragraph` but does not render any style. I have plenty of free time if you could point me in the right direction I would be happy to work on this.

**Comment by d249u7** [comment]
@DevinR528 How did you end up rendering the markdown?

**Comment by DevinR528** [comment]
Hmm, That was a while ago; I had to vendor it into the thing I was working I remember that. I also ended up writing a conversion function from mdcat or some other md parser to the tui color structures https://github.com/DevinR528/rumatui/blob/main/src/widgets/message/ctrl_char.rs
