### ISSUE TITLE
Text cannot be selected.

### ISSUE THREAD

**Issue by Yatekii** [fdehau/tui-rs#260]
**Describe the bug**
Text in the UI cannot be selected & copied.

**To Reproduce**
1. Print some text in a tui box.
2. Try to select it.

**Expected behavior**
Text can be marked and copied.

**Desktop (please complete the following information):**
 - OS: Linux
 - Terminal Emulator: Ubuntu Terminal
 - Font: Monospace
 - Crate version: 0.8.0
 - Backend: termion

It would be great if this could be done. I am not sure if this is a bug or really just impossible because of the ever updating text buffer of the terminal.

I would like to have this option as I build a logger from which I would like to copy paste.

**Comment by fdehau** [comment]
Could you show how you initialize your terminal ? If you use `input::MouseTerminal` from `termion` then your application will intercept all mouse events and thus disabling the "normal" behavior of your terminal of choice in response to mouse click or drag events.

**Comment by Yatekii** [comment]
Ah, this is indeed the case! Thanks for the tip! I will look into it.

**Comment by kotx** [comment]
I am also experiencing this issue with crossterm. Any workaround?
