### ISSUE TITLE
inconsistent Builder pattern

### ISSUE THREAD

**Issue by ratijas** [fdehau/tui-rs#28]
Some types in this library (e.g. `Style`, `Block`) use `mut self` in builder methods while others (e.g. `SelectableList`) go with `&'a mut self`. The latter style considered harmful, and I hate it a lot. This is what i had to make up to make things work for optional selection in a list view:

```rust
pub trait OptionalSelection<'a> {
    fn select_optional(&'a mut self, index: Option<usize>) -> &'a mut Self;
}

impl<'a> OptionalSelection<'a> for SelectableList<'a> {
    fn select_optional(&'a mut self, index: Option<usize>) -> &'a mut SelectableList<'a> {
        match index {
            Some(index) => self.select(index),
            None => self,
        }
    }
}
```

Of course it's more about the lack of such method in the library (which only has `select(&'a mut self, usize)`) than about the builder pattern and lifetimed references. But with a method that takes ownership and returns ownership, it's damn simple to store intermediate value somewhere and perform some conditional calls later.   Try that with `-> &'a mut Self`, I dare you!

Should I open a pull request about it? Could it be a breaking change? Is it acceptable?

**Comment by fdehau** [comment]
I see that you are not happy with the current design :). While I'm open to the idea of changing this since widgets are considered consumables, I will need some time (not too long hopefully) to review it and evaluate the impact. Could you also provide some relevant examples on how it might improve the library user's code in order to help us make our mind on this particular topic ?

**Comment by ratijas** [comment]
Or maybe `Modifier` pattern could be employed: reem/rust-modifier

(Of course, not.  Too much work and extra types without reasonable benefit.)

**Comment by fdehau** [comment]
This has been a long standing issue. Since multiple users have raised issues linked to the fact that the builder interfaces to create widgets didn't take ownership, I've finally moved to a consumable builder pattern for all widgets as you initially suggested.
