### ISSUE TITLE
Using line generation can cause panics due to subtraction with overflow

### ISSUE THREAD

**Issue by ClementTsang** [fdehau/tui-rs#280]
**Describe the bug**

Was eager to use the new line feature for graphs to avoid having to manually do the linear interpolation.  Unfortunately, using it has caused this following panic to show up after running for a bit:

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/blahaj/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.1/src/widgets/canvas/line.rs:82:30
   0: btm::panic_hook
             at src/main.rs:532
   1: btm::main::{{closure}}
             at src/main.rs:155
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   3: rust_begin_unwind
             at src/libstd/panicking.rs:378
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   5: core::panicking::panic
             at src/libcore/panicking.rs:52
   6: tui::widgets::canvas::line::draw_line_high
             at /home/blahaj/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.1/src/widgets/canvas/line.rs:82
   7: <tui::widgets::canvas::line::Line as tui::widgets::canvas::Shape>::draw
             at /home/blahaj/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.1/src/widgets/canvas/line.rs:52
   8: tui::widgets::canvas::Context::draw
             at /home/blahaj/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.1/src/widgets/canvas/mod.rs:279
   9: <tui::widgets::chart::Chart<LX,LY> as tui::widgets::Widget>::render::{{closure}}
             at /home/blahaj/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.1/src/widgets/chart.rs:503
  10: <tui::widgets::canvas::Canvas<F> as tui::widgets::Widget>::render
             at /home/blahaj/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.1/src/widgets/canvas/mod.rs:443
  11: <tui::widgets::chart::Chart<LX,LY> as tui::widgets::Widget>::render
             at /home/blahaj/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.1/src/widgets/chart.rs:491
  12: tui::terminal::Frame<B>::render_widget
             at /home/blahaj/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.1/src/terminal.rs:65
  13: <btm::canvas::Painter as btm::canvas::widgets::cpu_graph::CpuGraphWidget>::draw_cpu_graph
             at src/canvas/widgets/cpu_graph.rs:192
...
```
(rest of stack trace not included as it's a ton of closure and function calls in my own program)

Been also able to get a similar error with the `draw_line_low` function call sometimes.  In both cases, it's at a line where there's a usize - 1, which seems to be the culprit:

`y = if y1 > y2 { y - 1 } else { y + 1 };`

or 

`x = if x1 > x2 { x - 1 } else { x + 1 };`

Pretty sure this can just be fixed by just not subtracting from `x` or `y` if they're 0 (or just using something like `saturating_sub`), but wasn't really sure if that was how you would have wanted to fix this problem.  If that's fine, I can submit a PR.

**To Reproduce**
If possible include a code sample exhibiting the problem.

Currently not able to provide a full sample of what is causing it.

**Expected behavior**

Would have expected no panic to occur.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Terminal Emulator: kitty
 - Font: IBM Plex
 - Crate version: 0.9.1
 - Backend: crossterm

**Additional context**

**Comment by DarrienG** [comment]
Fix here: https://github.com/fdehau/tui-rs/pull/283

**Comment by DarrienG** [comment]
This was merged, so we can close this whenever :D

**Comment by ClementTsang** [comment]
Yep, will do.  Thanks!
