### ISSUE TITLE
[Question] What are x_bounds and y_bounds in Canvas?

### ISSUE THREAD

**Issue by rahulwa** [fdehau/tui-rs#286]
First time, I am working on any UI app so I don't know much about it. I tried to go through examples but unable to understand what are x or y bounds.
Also hacking on my first Rust project :)
Thanks in advance.

**Comment by fdehau** [comment]
Those are used to define the viewport of the canvas. Only the points whose coordinates are within the viewport are displayed. When you render the canvas using `Frame::render_widget`, you give an area to draw the widget to (a `Rect`) and the crate translates the floating point coordinates to those used by our internal terminal representation.

For example, when we draw the entire world map, the bounds are the ranges for latitude and longitude as floats:
```rust
            let canvas = Canvas::default()
                .block(Block::default().borders(Borders::ALL).title("World"))
                .paint(|ctx| {
                    ctx.draw(&Map {
                        color: Color::White,
                        resolution: MapResolution::High,
                    });
                    ctx.print(app.x, -app.y, "You are here", Color::Yellow);
                })
                .x_bounds([-180.0, 180.0])
                .y_bounds([-90.0, 90.0]);
            f.render_widget(canvas, chunks[0]);
```
If you were to "zoom" to a certain part of the world you may want to choose different bounds.

**Comment by gmale** [comment]
Great explanation. Is it possible to add that explanation to the docs for [x_bounds and y_bounds?](https://docs.rs/tui/0.14.0/tui/widgets/canvas/struct.Canvas.html#method.x_bounds)

**Comment by rishadbaniya** [comment]
> Great explanation. Is it possible to add that explanation to the docs for [x_bounds and y_bounds?](https://docs.rs/tui/0.14.0/tui/widgets/canvas/struct.Canvas.html#method.x_bounds)

was thinking the same
