### ISSUE TITLE
optional serde support for Style

### ISSUE THREAD

**Issue by extrawurst** [fdehau/tui-rs#292]
**Is your feature request related to a problem? Please describe.**
allowing the user of my application (based on `tui-rs`) to change its theme I need to be able to serialise `Style`.

**Describe the solution you'd like**
add the derive and bind it to a cfg so it can be an optional feature

**Describe alternatives you've considered**
Copy/Paste the types and use `serde`s `remote` serialisation support, but this is against *DRY* so it would be nice if this was supported by `tui-rs` natively

**Comment by fdehau** [comment]
Thanks for the feedback on this. I've implemented this in #307. Let me know what you think.

**Comment by extrawurst** [comment]
@fdehau thats awesome! LGTM. Thank you❤️

**Comment by extrawurst** [comment]
@fdehau when will this be released?
