### ISSUE TITLE
Inconsistent margin spacing in widgets

### ISSUE THREAD

**Issue by thorlucas** [fdehau/tui-rs#299]
**Describe the bug**
Widgets have inconsistent spacing on the margins in the blocks. Some widgets, for example the `Tabs`, have one column of spacing, while others like `Table` have no spacing. This just doesn't look right.

**Expected behavior**
All widgets should have consistent spacing (one or none) and optionally should be defined by the user for greatest flexibility.

**Screenshots**
<img width="771" alt="Screen Shot 2020-05-22 at 2 24 10 PM" src="https://user-images.githubusercontent.com/25698466/82710516-e8bc2480-9c37-11ea-9613-42797c94d9a2.png">

**Comment by fdehau** [comment]
I understand the issue. I think that a zero margin may be the best convention as it is adopted by most widgets at the moment. To my knowledge, only the `Tabs` widget has a default horizontal margin. The fix would be to:
* Add a `Margin` property to the widgets and default to zero margin in the `Default` implementation.
* Make it configurable through the builder.
* Take those margins into account in `Tabs::render`.
* Add one or two tests in a `tests/widgets_tabs.rs`.

Do you have an interest in tackling this particular issue ? Anyone whose reading could also take the lead if they want until I manage to get some time to look at it.

**Comment by thorlucas** [comment]
I can certainly give it a shot! Relatively new at Rust, but I think I'll manage just fine reading the implementation in the other widgets.

**Comment by thorlucas** [comment]
I've added in left margins and right margins are somewhat working, but there's a bit of an issue with right margins. Currently, tabs (and it appears other widgets too maybe?) simple write off of the buffer, not truncating the string if it's too long.

This causes the tab titles to write onto the edge of the block, like so (screenshot taken without any modifications):

<img width="430" alt="Screen Shot 2020-05-27 at 10 14 58 PM" src="https://user-images.githubusercontent.com/25698466/83101588-81eba080-a067-11ea-9e0e-d4995b9baaff.png">

Which is undesirable, and is made visually even worse when using right margins (screenshot taken after margin modifications, with margin size of 2):

<img width="463" alt="Screen Shot 2020-05-27 at 10 16 13 PM" src="https://user-images.githubusercontent.com/25698466/83101657-ae072180-a067-11ea-9d55-5e179e6a5aaf.png">

The difficulty is due to how we want to handle truncation. With unicode some characters can occupy variable size, so it's not as simple as string slicing, as I'm sure you know. We could use something like [unicode_truncate](https://docs.rs/unicode-truncate/0.1.1/unicode_truncate/)  to handle this, but it could add a little bloating and it's certainly slower. The speed impact shouldn't be too bad if we first check if truncation is required before doing so, but I don't want to add dependencies without approval.

**Comment by fdehau** [comment]
The functionality you are asking for is already provided by `Buffer::set_stringn` which take an additional width parameter that is your width "budget" to draw the string. If the budget is exhausted the function stops printing. This width budget is usually the diff between the right most bound of the area you are drawing too and your current horizontal offset.

**Comment by thorlucas** [comment]
Great! All tests are passing and it looks good.

<img width="551" alt="Screen Shot 2020-05-28 at 2 12 35 AM" src="https://user-images.githubusercontent.com/25698466/83122573-b4f25c00-a088-11ea-9fd8-2c13b38b3324.png">

Would you like me to submit a PR of just the tabs widget, or should I implement margins on all other widgets before submitting PR?

**Comment by teohhanhui** [comment]
Margins on any widget would be so useful! :heart:

**Comment by thorlucas** [comment]
@teohhanhui Well you're in luck because I'm working on it actively and it should be done fairly soon! Adding vertical and horizontal margins. Done so far on tabs, working on the rest of the widgets now.

**Comment by thorlucas** [comment]
I've ran into an ambiguity and I'd like to poll the community to see how it should be handled:

Tables and lists have a selector. Right now, the default functionality is to provide a sort of margin on the left to accommodate the width of the selector. It looks like this:

<img width="1178" alt="Screen Shot 2020-06-02 at 11 03 22 AM" src="https://user-images.githubusercontent.com/25698466/83553834-ad83e600-a4c0-11ea-8e74-a1f13750ab13.png">

The question is what to do when it comes to margins. There are a few options:

1. **Enforce margins.** Throw an error if the horizontal margin provided is not sufficient to fit the selector.

2. **Add margins.** Simply add the width of the selector and the margin. If you have a margin width of 2, and a selector width of 1, the final left margin would be 3.

3. **Max margins (probably best).** If you have a margin width of 2, and a selector of 1, the margin is 2. If your selector is instead 3 wide (bigger than 2), then the left margin will be 3, but the right margin will remain 2.

**Comment by teohhanhui** [comment]
Option 4: Just treat the selector as if it's part of the row's content. Personally, I think this is the most intuitive and predictable behaviour. Option 2 and 3 are a bit surprising (too much magic, which makes it harder to have precise control).

> Currently, the selector margin only affects the data, not the header. ... If we went with a solution like 3, do you think that the header margin should also reflect the resulting margin?

We can add the selector width to the content width, when going with option 4.

**Comment by fdehau** [comment]
@thorlucas I would prefer separate PRs as I don't think that we have the same problem (if any) on all widgets. Regarding your observation on the table margins (or padding, it's true that the name can be confusing for people used to css), an error should never be thrown on narrow areas (panics are bugs) the rendering should simply be skipped and the margin may not take the selector into account if we want a similar behavior across widgets. The first thing that comes to my mind would be (excuse the ugly diagram): 
![table](https://user-images.githubusercontent.com/10096255/83688516-d655c980-a5ed-11ea-85c9-f42d73fb8ba9.png)

**Comment by teohhanhui** [comment]
@fdehau That diagram is the same as what I've described as option 4.

**Comment by fdehau** [comment]
@teohhanhui Yeah sorry I went through your comment a bit too quickly and understood something slightly different. I'm glad we agree :).

**Comment by thorlucas** [comment]
Option 4 it is! That’s actually equivalent to what I said in my option 2 — just add the two widths for the left margin.

@fdehau you would prefer separate PR’s for each widget? I was just going to make all widgets work consistently in terms of specifying margins. 

I can make the bug fix that closes this issue one PR (changes tabs margins to 0), and a separate PR to add customizable margins to all widgets, if that’s what you mean?
