### ISSUE TITLE
Is there a way to ensure canvas text don't overlap?

### ISSUE THREAD

**Issue by yimmt** [fdehau/tui-rs#302]
I am trying to draw random text onto a canvas. However, there is an issue when I draw text with relatively close coordinates due it causing the words to overlap each other. 

It seems to me that there isn't a way to get the dimensions of the text, like you can with Rectangle. Is there a way you can get the full 2D size of the text you are drawing on the canvas? Or is there a way to even check if two texts overlap with each other, so I wouldn't draw one of them?

**Comment by fdehau** [comment]
There is no way to check that two texts overlap at the moment. You might get the information you want using two things:
- The location of the label in terms of (row, cols) on its internal grid given its floating points coordinates can be obtained using the `widgets::canvas::Painter` that can itself be built from the given context.
```rust
canvas.paint(|ctx| {
   let painter = Painter::from(ctx);
   let (row, col) = painter.get_point(1.5, 2.75);
}
```
- The width of a string can be retrieved using `UnicodeWidthStr`.
