### ISSUE TITLE
[Feature request] Area chart

### ISSUE THREAD

**Issue by teohhanhui** [fdehau/tui-rs#306]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It'd be nice to have a new `GraphType::Area` which fills the area under the dataset's line.

**Describe alternatives you've considered**
Doing this manually would be tedious.

**Additional context**
Stacked area charts would be even cooler: https://www.r-graph-gallery.com/136-stacked-area-chart.html

**Comment by fdehau** [comment]
While `GraphType:Area` shouldn't be too complicated to implement, stacked area charts may be a bit more complex as they imply a link between datasets and it is not the case at the moment. I need to think about it.

I wonder if the output would be nice though as there is no way to properly fill the area under a line. @teohhanhui Have you found other examples in terminal libraries ?
