### ISSUE TITLE
StatefulWidget should not take &mut State but use interior mutability

### ISSUE THREAD

**Issue by teohhanhui** [fdehau/tui-rs#311]
**Is your feature request related to a problem? Please describe.**
I don't want to pass a `&mut` of my app's state to my `draw` function, as it's logically incorrect. The `draw` function should not be able to mutate app state.

**Describe the solution you'd like**
I'm still a newbie to Rust so I'm not sure if I'm making any sense, but it seems to me that interior mutability would help. Is it possible here?

**Describe alternatives you've considered**
I can wrap the state as e.g. `RwLock<ListState>`, but it is awkward.

**Additional context**
N/A

**Comment by fdehau** [comment]
> I don't want to pass a &mut of my app's state to my draw function, as it's logically incorrect. The draw function should not be able to mutate app state.

While I agree with the intention of this comment, I think that there is a bit of nuance to this problem. You should not have to mutate your app state during the draw call but some state needs to be kept around between two draw calls for some UI patterns ([this](https://docs.rs/tui/0.9.5/tui/widgets/trait.StatefulWidget.html) part of the documentation covers with more details). Given the current architecture of the crate (immediate mode), I've chosen to make this widget state management explicit, if you need one of the patterns requiring such state then you need to make sure to save it somewhere. You can make the choice to have it as part of your app state but you could also put it in an other struct that only contains state related to the UI. Then you can have simple borrow on your app state and a mutable borrow on your UI state. I try to let users organize this kind of state management as they see fit. In both cases, the crates still aims to make the UI a straightforward representation of your current app state through widgets "commands" and it is a good practice to keep most of your state management outside of the `draw` function.

I'm not sure too see how your proposition could make this simpler but if you could give some more details and/or code samples that may help me to understand your point :).

**Comment by teohhanhui** [comment]
If `ListState` has interior mutability then it can be passed in as shared reference, thus freeing the user from this concern. As indeed, the offset that needs to be mutated is entirely internal and currently not even accessible in any form.

**Comment by fdehau** [comment]
Again I fail to see your point. "interior mutability" can be materialized in a lot of ways so could you provides a code sample of what the code would look like with your proposed change. Where would you store this associated state then ?

**Comment by teohhanhui** [comment]
```rust
#[derive(Debug, Clone)]
pub struct ListState {
    offset: RefCell<usize>,
    selected: Option<usize>,
}
```

**Comment by teohhanhui** [comment]
Basically we pass `state` as shared reference, this truly enforcing that state changes must be made outside of draw. The escape hatch is of course interior mutability.

**Comment by fdehau** [comment]
Ok I understand your point now but then it is a tradeoff between enforcing something that I only consider a best practice by lying to the borrow checker and an api that clearly communicates what's going on when your render a stateful widget (ie smth is going to be mutated). That could be good evolution though and I'm starting to regret not having this kind of input earlier :). Have you tried to perform this change already in a wider example (e.g one of the demo) ?

**Comment by teohhanhui** [comment]
It's not lying to the borrow checker. It's a contract. The difference may not be obvious with our own `ListState`, but this changes the contract with custom stateful widgets. The current contract tells authors of custom widgets that it's okay to mutate state when drawing, which is not the intention at all.

**Comment by fdehau** [comment]
Sure and I totally agree with you. Given the current usage of those additional states and the private nature of some of their properties, your solution is better at enforcing the contract. By lying to the borrow checker, I was implying that we move to a dynamic check but as you have highlighted this is totally safe to do and that's one of those cases why these escape hatches were introduced in the first place. Again the more I think about it the more it appears as a better solution.

**Comment by MrGibus** [comment]
I might be missing something here, but if the `selected` field was part of the widget and not the state you wouldn't need to pass mutable reference of your entire app. I can't see any scenario in which you'd need to change `selected` between draw calls.

Really the name `StatefulWidget` is confusing because there are many widgets with states that can be rendered just fine without the trait.
