### ISSUE TITLE
Table panics on narrow areas

### ISSUE THREAD

**Issue by thorlucas** [fdehau/tui-rs#314]
**Describe the bug**
Table widgets panic when the terminal gets too narrow.

**To Reproduce**
Run `cargo run --example table`. Shrink the terminal width to about 68. It should panic and just close out.

**Expected behavior**
Widgets should never panic on rendering.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - iTerm2 3.3.10, Terminal 2.10
 - 0.9.5
 - termion

Additionally, no test exists asserting that tables should not panic on narrow areas in `tests/widgets_table.rs`, while this test exists in `tests/widgets_tabs.rs`. This test needs to be implemented for every widget.

**Comment by fdehau** [comment]
Thanks for reporting this. As you have already found a reproducible way to trigger this panic and where the tests are missing, would you be inclined to work on this ? Otherwise, I've labeled this as a good first issue if anybody want to take it.

**Comment by thorlucas** [comment]
I’m likely going to have to deal with this on my margins PR anyway, so I’ll probably end up fixing this too.

**Comment by fdehau** [comment]
That would be great but I would encourage you to submit different PRs :)

**Comment by thorlucas** [comment]
Will do!

**Comment by fdehau** [comment]
This should have been addressed as part of #417
