### ISSUE TITLE
RFC: Text

### ISSUE THREAD

**Issue by fdehau** [fdehau/tui-rs#315]
I've started implementing a possible solution for the current styling limitations reported in #304 and #88. People want to use ansi escape codes but the current accepted solution is to use what is provided at an higher level by tui: `Style`, `Color`, `Modifier`. However, some complex styling scenarios are not possible with the current primitives. Let's say I want to have a `Block` with a white title and a the first letter in bold red. This is not possible at the moment as you can only provide a single `Style` object for the whole title. My plan is to introduce three new primitives in tui to cover all needs in the different widgets:

- `Span` which is the smallest unit in a text. It is a `Cow<str>` that can be associated with a style.
- `Spans` which is a sequence of `Span`.
- `Text` which is a sequence of `Spans`.

The primitives allows the end users to build complex styled strings and by using a specific primitive widgets may convey the styling capabilities of their properties (Span = unique style for the whole string, Spans = multiple styles on a single row, Text = multiple styles on multiples rows).

By providing various `From` implementations, the widgets api can also be more flexible. For example, for a `Block`,  all those calls could be valid:

```rust
// Raw string no styling => converted to Spans with a single unstyled Span.
Block::default().title("My title");
// String with unique style => converted to Spans with a single styled Span.
Block::default().title(Span::styled("My title", Style::default().fg(Color::Red));
// String with multiple styles => converted to Spans with multiple Span.
Block::default().title(vec![Span::styled("My", Style::default().fg(Color::Red)), Span::from("title")]);
```

Feedback more than welcome !

**Comment by teohhanhui** [comment]
I think `Fragment` should be `Span`. The definition is exact and it matches HTML. "Fragment" seems pretty vague.

**Comment by acheronfail** [comment]
Whatever we end up calling it, I'd really love this feature!

Right now I'm rendering items in a `List`, and it would be amazing to be able to have multiple styles in each line. For example, I have this here: https://github.com/acheronfail/repgrep/blob/fae12f50c9879127ba17d9c19383dad680d69a5f/src/model/item.rs#L148-L153 which means I can only color the _entire_ line in one style, not portions of it.

**Comment by jacobrosenthal** [comment]
I think I could use this as well. Not necessarily for styling, but more as a method to render multiple line wrapping text fields ala paragraph.

**Comment by fdehau** [comment]
@teohhanhui Thanks for the `Span` suggestion, I've replaced `Fragment` with it. I want to add `Line` and `Text` to let widgets advertise which type of string they accept, e.g a `Block` accepts a title which should fit on a single `Line` while a `List` might accept `Text` items to support multi-lines items.

**Comment by teohhanhui** [comment]
Would `Text` and `MultilineText` be clearer?

**Comment by fdehau** [comment]
I've put some additional work in the PR. The most text heavy widgets have been migrated (with the exception of `Table`). You can see a summary of the changes in the PR description. I still need to document all the new stuff and add maybe some tests to cover new edge cases but if some of you are up for an early review be my guest :).

**Comment by fdehau** [comment]
The documentation has been added. The new api is now stable after many iterations. I'm going to merge this in a few days.
