### ISSUE TITLE
Table with differently styled columns?

### ISSUE THREAD

**Issue by murlakatamenka** [fdehau/tui-rs#330]
Currently a table expects `Row`s with unified style only, i.e.

```rust
let Row = Row::StyledData(<iterable _items>, <style>);
```
and it's not possible to have row items of different style, right?

These issues gotta be relevant here: #239 and #315, there are discussions of possible `Item` / `TextCell` there.

**Comment by dvoytik** [comment]
I'm interested to use this. I can try to implement the feature if nobody is working on it.

**Comment by leebenson** [comment]
@dvoytik, that'd be awesome, thanks!

**Comment by fdehau** [comment]
This should have been addressed as part of #417
