### ISSUE TITLE
question: is it possible to draw line charts without axes?

### ISSUE THREAD

**Issue by Suyash458** [fdehau/tui-rs#331]
I've tried `SparkLine` but, it renders bars. Can the axes in `Chart` be removed to draw something like below?
![image](https://user-images.githubusercontent.com/7749510/86481781-49c63480-bd6e-11ea-9743-4c6875a74ed9.png)

**Comment by fdehau** [comment]
Yes it should be possible. Use a `Chart` widget and use `Axis` where you only specify bounds (no title, no labels, ...), e.g `Axis::default().bounds([0.0, 20.0])`. Let me know if that's what you wanted.

**Comment by Suyash458** [comment]
@fdehau that's exactly how I wanted it to look, thank you!
