### ISSUE TITLE
Change legend position on Chart

### ISSUE THREAD

**Issue by HiDefender** [fdehau/tui-rs#335]
Would it be possible to add a function that allows the legend of a Chart to be positioned somewhere other than the top-right corner?

It could be an enum with 4 positions, one for each corner.
9 positions would also be nice for graphs where all corners should be visible:
TopLeft    -    TopCenter    -     TopRight
MidLeft    -    MidCenter    -    MidRight
BottomLeft - BottomCenter - BottomRight

**Comment by fdehau** [comment]
It is definitely possible but also probably very time consuming given the amount of cases that need to be tested. I'm not willing to put any work on this at the moment but I would accept a PR.
