### ISSUE TITLE
v0.10 fails to compile

### ISSUE THREAD

**Issue by TheKevJames** [fdehau/tui-rs#342]
**Describe the bug**
Version v0.10.0 causes a compilation error. Bumping my demo app to use `tui==0.10` gives the following error:

```
error[E0599]: no associated item named `MAX` found for type `usize` in the current scope
   --> /Users/kevin/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.10.0/src/buffer.rs:266:47
    |
266 |         self.set_stringn(x, y, string, usize::MAX, style);
    |                                               ^^^ associated item not found in `usize`
    |
help: you are looking for the module in `std`, not the primitive type
    |
266 |         self.set_stringn(x, y, string, std::usize::MAX, style);
    |                                        ^^^^^^^^^^^^^^^

error: aborting due to previous error
```

This seems to have been caused by [this change](https://github.com/fdehau/tui-rs/commit/96c6b4efcbf7ec1e4ceb258f2eba05d2cb3c540d#diff-cc80d88b5d0d9034b72929a62e9cded8L2), where the `use std::usize` was removed.

**To Reproduce**
As far as I can tell, this error occurs before it gets to any of my code, but the relevant app is [here](https://github.com/TheKevJames/tools/tree/master/cctui). 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Terminal Emulator: Alacritty
 - Font [e.g Inconsolata, Monospace]: Meslo
 - Crate version [e.g. 0.7]: 0.10
 - Backend [e.g termion, crossterm]: termion

**Comment by salkin-mada** [comment]
I get the same error [E0599] with all usage of tui and the termion demo
Jumped back to version 0.9.5 - all is good.

**Comment by fdehau** [comment]
Could you precise the version of rustc you are using ? tui requires 1.44+ from 0.10.0. I made this clearer in #346.

**Comment by salkin-mada** [comment]
Ah I missed that. Was using 1.43. 
Updated `rustc` to 1.45.1 and demo is working perfectly with tui v0.10.0
Thanks.
