### ISSUE TITLE
Werid display when used in `screen`

### ISSUE THREAD

**Issue by DataCorrupted** [fdehau/tui-rs#344]
**Describe the bug**
When using command-line tool `screen`, the displayed result is werid and buggy.
The original terminal is not hidden.

![image](https://user-images.githubusercontent.com/23134872/88488361-ac5fba00-cf41-11ea-9e0c-dcf443de9f10.png)
![image](https://user-images.githubusercontent.com/23134872/88488392-e92bb100-cf41-11ea-8886-bdbbd96dde87.png)

Notice:

1. The upper left part of the screenshot, where the result of `ls` is shown.
2. The bar chart's x-axis
3. The percentage number in progress bar.

**To Reproduce**
```
sudo apt install screen
screen -S tui-rs
cargo run --example termion_demo --release -- --tick-rate 200
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 2004
 - Terminal Emulator: Reproduced on default terminal & Terminator(`sudo apt install terminator`)
 - version: 0.9.0
 - Backend: termion

**Additional context**
I guess it's because `screen`' and termed conflicted when hooking stdout & stderr?

**Comment by fdehau** [comment]
The demo is using `AlternateScreen` and I think the `altscreen` option of `screen` is off by default. You can either enable this option of `screen` or stop using `AlternateScreen` and clear the terminal manually before the first draw.

**Comment by DataCorrupted** [comment]
Thanks for your hint. I wasn't sure what `AlternateScreen` is but now I know. You are right, `altscreen` is off by default.

In case anyone gets here in the future, [here](https://stackoverflow.com/questions/17868652/screen-how-to-turn-on-alternate-screen) is how to turn on `altscreen` in `screen`

**Comment by asomers** [comment]
Enabling altscreen is an effective workaround.  However, this still seems like a bug in tui-rs, or maybe termion.  They should work regardless of screen's configuration.  It's notable that tui-rs's crossterm, curses, and rustbox demos do not exhibit this problem.  Nor do any of termion's demos.
