### ISSUE TITLE
Document x, y coordinates

### ISSUE THREAD

**Issue by Luro02** [fdehau/tui-rs#352]
It would be nice if one could document how the x and y coordinates are defined. (Beginners might not know about it and well the more documentation the better).

#### What I think when I see x and y:

![image](https://cdn4.vectorstock.com/i/1000x1000/48/48/x-and-y-axis-with-numbers-vector-7804848.jpg)
![image2](https://www.freemathhelp.com/images/lessons/xy1.png)

#### What it actually is:

![image3](https://hendrix-cs.github.io/csci150/assets/images/coordinates.png)

#### Relevant structs
- `tui::layout::Rect`
- `tui::widgets::canvas::*`

**Comment by fdehau** [comment]
I agree the axis can be confusing. The main issue is that most the widgets use `(x, y)` for something that should actually be `(col, row)`. The canvas uses Cartesian axis for the data though.

Is this something you would help clarify in the documentation ?

**Comment by Luro02** [comment]
I am not sure if I am the correct person for this. I have absolutely no clue about this crate (never used it, just looked a bit through the docs).

**Comment by fdehau** [comment]
Ok sure thing. Thanks for the report anyway. I've requalified the issue in the meantime.

**Comment by stbor** [comment]
Need terms and conditions

**Comment by fdehau** [comment]
@stbor I think the best approach would be to have a different vocabulary for each coordinates system:
- We should use the row and column denomination for everything that deals with the grid system we are using to represent the terminal (i.e all widgets rendering code).
- We should use x, y when we are referring to a more traditional Cartesian coordinates system (i.e the abstraction Canvas is built on top of).
While this task should be easy as it should only be basic substitutions, it is probably big given the amount of code to change.
