### ISSUE TITLE
Question about leaving and re-entering.

### ISSUE THREAD

**Issue by eemed** [fdehau/tui-rs#355]
Hi,
I am using crossterm backend. TUI is only used for draw calls, otherwise I setup my terminal using crossterm

    let mut stdout = io::stdout();
    execute!(stdout, terminal::EnterAlternateScreen).unwrap();
    execute!(stdout, cursor::Hide).unwrap();
    execute!(stdout, terminal::Clear(terminal::ClearType::All)).unwrap();
    terminal::enable_raw_mode().unwrap();

I'm trying to open a file using $EDITOR. I tried to disable alternatescreen and rawmode before opening up the $EDITOR and restoring them after but after quitting the $EDITOR. I can only see changes rendering to the screen.

How can I re-render everything back after quitting the $EDITOR?

EDIT: Got it working by looking at the source. It seems it is always diffing the buffers, but I want to re draw everything. I added an empty `draw()` call to get the diff result to be everything. This feels like a workaround, should this be supported?

**Comment by fdehau** [comment]
This is a case I haven't thought of to be honest :). I think one of the issue is that `terminal.clear` does not keep the internal buffers in sync. Would the changes in #360 help you ?

**Comment by eemed** [comment]
Looks like #360 would fix it.

**Comment by fdehau** [comment]
Ok I merged it to master. Let me know if you manage to play with this and if this effectively fix your issue.

**Comment by eemed** [comment]
I tested it and it's fixed.
