### ISSUE TITLE
Document that Braille patterns may require font overrides

### ISSUE THREAD

**Issue by ssb22** [fdehau/tui-rs#356]
As discussed on https://github.com/cjbassi/ytop/issues/79 the use of Braille patterns to plot graphs may require the terminal to be set to use a font like Symbola for that part of the Unicode range.  Some other fonts also display the “off” dots (for example as empty circles)—Braille patterns are somewhat less useful for graph plotting if a font like that is selected.  I'd like to propose that this be mentioned somewhere in the documentation so that developers using this library know they might have to warn their users that the Braille patterns might not show as intended, depending on one's choice of fonts.  (See screenshots on the ytop issue linked above.)

The Braille Patterns block was originally designed for representing Braille, for example in books that teach sighted readers how to transcribe things into Braille.  It was not originally designed just for graphical patterns.  So it's understandable if some fonts show the “off” dots and others do not.

Thanks.

**Comment by fdehau** [comment]
Thanks for the report. I'm already aware of the issue as illustrated by the `--enhanced-graphics` option of the demo, which allow you to [disable braille patterns](https://github.com/fdehau/tui-rs/blob/ecb482f2978bfbfe396fa29968a4b72e01432c86/examples/demo/ui.rs#L199) and other less supported unicode graphemes. Although, it's true that the documentation may need some improvements on the topic.

Is this something you were willing to help ?
