### ISSUE TITLE
Don't consume widgets when rendering them

### ISSUE THREAD

**Issue by dotdash** [fdehau/tui-rs#357]
In earlier versions it made sense to consume the widget when rendering, as many widgets only had an iterator that produced their contents, so it was gone when rendering was done. But since version 0.10, most (all?) widgets actually own their contents in a reusable way, so it would make sense to me to change the render function to take the widget by (mutable?) reference. This would allow ot reuse the widgets, avoiding the need to recreate them each render cycle, which is quite allocation heavy given the new `Text`/`Spans`/`Span` layout.

**Comment by fdehau** [comment]
In `tui`, widgets are meant to be compact commands to draw common UI elements that can be found in a terminal user interface. Thus they hold the minimum amount of state as possible. The proposed change would go against that principle.

The fact that some widgets require `Vec` instead of iterators only make it public that they need to know the entire input data before starting to draw something. Beside `Span`s are `CoW` types so you should be able to create a `Text` where you only allocate for the string references not their content themselves.

Is this question motivated by a perf issue you were directly impacted by (i.e I want to see numbers) or just an issue with the current design ?

**Comment by Arnavion** [comment]
>The fact that some widgets require `Vec` instead of iterators only make it public that they need to know the entire input data before starting to draw something.

Coult they (looking at `List` and `Text` specifically) at least be changed to take `&[T]` instead of `Vec<T>`, so that there isn't a new allocation for every frame?

**Comment by happycoder97** [comment]
I felt this is a design issue so I created a fork here https://github.com/happycoder97/tui-rs.
Let me know your feedback :)

Rationale:
In my apps, I am getting input from somewhere else in the app, and then modifying the concrete structs that implement Widget there.  
So I can put the Widget state in that struct itself.

<details><summary>Example code</summary>
<p>

```rust
#[derive(Default, Copy, Clone)]
pub struct TasksWidget {
    active_idx: Option<usize>,
}

impl StatefulWidget for TasksWidget {
    type State = Vec<Task>;

    fn render(&self, area: Rect, buf: &mut Buffer, state: &mut Self::State) {
        (self as TasksWidget).render(area, buf, state);
    }
}

impl TasksWidget {
    fn render(&self, area: Rect, buf: &mut Buffer, state: &Vec<Task>) {
        let block = Block::default().borders(Borders::ALL);
        block.render(area, buf);
        self.render_heading(area, buf);
        let tasks = state;
        for (i, task) in tasks.iter().enumerate() {
            let is_active = self.active_idx == Some(i);
            let task_area = Rect {
                width: area.width,
                height: 5,
                x: area.x,
                y: area.y + 3 + (i as u16) * 5,
            };
            self.render_task(task, is_active, task_area, buf);
        }
    }

    fn render_heading(&self, area: Rect, buf: &mut Buffer) {
        // snip
    }

    fn render_task(&self, task: &Task, is_active: bool, area: Rect, buf: &mut Buffer) {
        // snip
    }

    pub fn select_up(&mut self, _tasks: &Vec<Task>) {
        self.active_idx = match self.active_idx {
            None => None,
            Some(idx) => Some(idx + 1),
        }
    }

    pub fn select_down(&mut self, tasks: &Vec<Task>) {
        self.active_idx = match self.active_idx {
            None => Some(0),
            Some(idx) => Some(idx + 1),
        };
        if let Some(idx) = self.active_idx {
            if idx >= tasks.len() {
                self.active_idx = None;
            }
        }
    }

    pub fn get_selected_idx(&self) -> Option<usize> {
        self.active_idx
    }
}
```

</p>
</details>

I'm also planning to make `StatefulWidget::render()` take `&State` instead of `&mut State`.

**Comment by gauteh** [comment]
Hi, I am having performance issues with a huge List (100k entries). Using the demo event handler the 1 sec tick causes consistent 20% cpu usage. There could be other things as well, like scrolling and selecting, but just regular re-drawing causes issues. Why does the List need to have all its elements? Knowing size it should be sufficient to render only the visible ones. Thanks for a very easy to use toolkit!

**Comment by philippeitis** [comment]
@gauteh 

Not quite the same thing, but if you're having performance issues, a solution might be to generate a small list which only contains the data you need when rendering, and update it when your selection changes. My solution is to have a source list which is a regular Vec, and create a new List object using a slice of my source data - so the list itself will be really small, and it would not be necessary to scroll through ~100k elements in the List object when rendering the text.

My code looks somewhat like this - when the selection is moved up or down, self.start would adjusted to move the visible window up and down, and self.selected would be adjusted if your selection moves within the window:

```rust
fn render_columns<B: Backend>(&self, f: &mut Frame<B>, chunk: Rect) {
    let select_style = Style::default()
        .fg(self.style.selected_fg)
        .bg(self.style.selected_bg);

    let list = List::new(
        self.data[self.start..self.start + chunk.height as usize].iter()
            .map(|item| ListItem::new(item.to_string()))
            .collect::<Vec<_>>(),
    )
        .block(Block::default().title(Span::from(self.title.to_string())))
        .highlight_style(select_style);

    let mut selected_row = ListState::default();
    selected_row.select(self.selected);
    f.render_stateful_widget(list, chunk, &mut selected_row);
}
```

**Comment by gauteh** [comment]
Thanks! I tried out cursive, but I essentially have to solve it in a
similar way (except that I store the rendered lines in a Vec and only print
the visible ones).

tor. 12. nov. 2020, 01:22 skrev philippeitis <notifications@github.com>:

**Comment by nifker** [comment]
I can agree with @itsfarseen and think its not just about the built-in widgets but more about widgets from the designer themself or even third-party widgets, should make it much easier to implement and use when widgets can be reused.
