### ISSUE TITLE
It looks like the 0.10.0 Jul 18, 2020 has a Cargo.lock

### ISSUE THREAD

**Issue by dschuyler** [fdehau/tui-rs#358]
I'm rather new to Rust, so this may be a bogus report, but:
It looks like the 0.10.0 Jul 18, 2020 crate is being distributed with a Cargo.lock.
If I understand correctly, libraries are discouraged from distributing a Cargo.lock.

**Comment by fdehau** [comment]
Thanks for bringing this up. I was not aware of this but I think this is [the default behavior](https://github.com/rust-lang/cargo/blob/5165270dd4ff92deab0af23ca9ee317714d2e045/src/cargo/core/package.rs#L250) of `cargo` when it publish a package including examples (which is the case of `tui`). My understanding is that the lock file is ignored during the build process though.
