### ISSUE TITLE
Eliminate tiny chance of panic in demo

### ISSUE THREAD

**Issue by nthparameter** [fdehau/tui-rs#363]
In examples/crossterm_demo.rs there is a loop to check the elapsed time:
```
        loop {
            // poll for tick rate duration, if no events, sent tick event.
            if event::poll(tick_rate - last_tick.elapsed()).unwrap() {
                if let CEvent::Key(key) = event::read().unwrap() {
                    tx.send(Event::Input(key)).unwrap();
                }
            }
            if last_tick.elapsed() >= tick_rate {
                tx.send(Event::Tick).unwrap();
                last_tick = Instant::now();
            }
        }
```
In that loop `tick_rate - last_tick.elapsed()` may try to subtract larger value (`last_tick.elapsed()`) from a smaller value (`tick_rate`). If this occurs the program panics due to:
https://doc.rust-lang.org/src/core/time.rs.html#414-448
and
https://doc.rust-lang.org/src/core/time.rs.html#748-755

If I understand correctly (and I may be missing something), the above could be fixed by changing the loop to:
```
        loop {
            // poll for tick rate duration, if no events, sent tick event.
            let elapsed = last_tick.elapsed();
            if elapsed  >= tick_rate {
                tx.send(Event::Tick).unwrap();
                last_tick = Instant::now();
            } else if event::poll(tick_rate - elapsed).unwrap() {
                if let CEvent::Key(key) = event::read().unwrap() {
                    tx.send(Event::Input(key)).unwrap();
                }
            }
        }
```
The change involves grabbing the elapsed value and checking that it is strictly less than tick_rate before doing the subtraction.

P.S. for the error to occur, the elapsed time would need to be just shy of the tick_rate and one point, so that it was just over the tick rate during the subtraction. That's going to be very, very rare. But, the fix to make it never happen, seems reasonable. What to you think?

**Comment by fdehau** [comment]
Thanks for raising my attention to this issue. I've created a fix here #380 using a different approach but the intent is the same.
