### ISSUE TITLE
Single line paragraphs with a block aren't rendered

### ISSUE THREAD

**Issue by dotdash** [fdehau/tui-rs#366]
I want to realize a layout like this:
```
┌────────────────────────┐
│ Tabs                   │
│ Single line paragraph  │
│ List                   │
│ ...                    │
└────────────────────────┘
```

**To Reproduce**

I have constraints and widgets like this:

```rust
let constraints = [
    Constraint::Length(2),
    Constraint::Length(1),
    Constraint::Min(0),
];

let tabs = Tabs::new(/*...*/).block(Block::default().border(Border::LEFT | Border::TOP | Border::RIGHT));
let para = Paragraph::new(/*...*/).block(Block::default().border(Border::LEFT | Border::RIGHT));
let list = List::new(/*...*/).block(Block::default().border(Border::LEFT | Border::BOTTOM | Border::RIGHT));
```

**Expected behavior**
Output like the example above

**Actual output**
```
┌────────────────────────┐
│ Tabs                   │

│ List                   │
│ ...                    │
└────────────────────────┘
```

**Desktop (please complete the following information):**
 - OS: Linux (Debian Sid)
 - Terminal Emulator: termite
 - Font: Input Mono 10
 - Crate version: 0.10.0
 - Backend: termion

**Additional context**
Looking at the render function, it seems that blocks that are less than 2 units in either width or height aren't rendered at all and report an inner area of (0, 0), which looks like a bug to me as it seems fine to render a block of height 1 if the border is only on the left and right sides.

**Comment by fdehau** [comment]
Yes that's definitively not the expected behavior here and I think you already found the root cause of the issue. Without undermining this bug though, I'm curious if something would help you achieve what you want in the meantime:
```rust
let constraints = [
    Constraint::Length(2),
    Constraint::Length(1),
    Constraint::Min(0),
];
let chunks = Layout::default()
    .direction(Direction::Vertical)
    .margin(1)
    .constraints(&containts)
    .split(area);
f.render_widget(Block::new().borders(Borders::ALL), area);
// render other widgets in chunks
```
