### ISSUE TITLE
Option for Gauge to use Unicode Block Elements

### ISSUE THREAD

**Issue by fabi321** [fdehau/tui-rs#367]
I come from a [python TUI library](https://github.com/urwid/urwid/blob/master/urwid/graphics.py#L264) where you have the option to use Unicode Block Element letters (ex. U+2588 to U+258F, see [Block Elements](https://en.wikipedia.org/wiki/Block_Elements)) to have a much finer graduation.

It would be nice to have a method to activate Unicode Block Elements.

I tried to implement it in my own library, but every approach I took didn't work well.

**Comment by DashEightMate** [comment]
I've made this pr https://github.com/fdehau/tui-rs/pull/377, it needs a bit of improvement but it's a very solid start.

**Comment by fdehau** [comment]
Closed in #377
