### ISSUE TITLE
is there a way to render the full app, instead of just the changes

### ISSUE THREAD

**Issue by n1ck-i** [fdehau/tui-rs#369]
**Is your feature request related to a problem? Please describe.**
In my current application the user can open the config file in vim.
Now when returning to the app content only appears after it changes.

I read this in a reply to issue #281 
> Why is that ? Because tui buffers all the output to only emit the necessary ansi escapes commands required to reflect the changes between two draw calls.

My question is: Is there a way to force tui to render the entire app?

**Describe the solution you'd like**
It would be nice to have a function/call to render the entire app.

**Describe alternatives you've considered**
I've tried `terminal.clear()`, `terminal.current_buff_mut().reset()` and indiviualy resetting all cells but it always results in the initial output where only new changes are rendered.

I've implemented a temporary fix by rendering a block at the very start of my draw routine, which spans the entire frame and uses values for fg, bg and modifier that are used nowhere else so everything is a change.
But this feels like a heck and also creates an annoying flash when the "reset block" is rendered.

**Comment by extrawurst** [comment]
You can force a redraw by manually calling `terminal.resize`
See https://github.com/extrawurst/gitui/blob/master/src/main.rs#L185

**Comment by n1ck-i** [comment]
Thanks, that solved it
