### ISSUE TITLE
Box drawing characters are fullwidth on some CJK Windows Conhost and cause broken layout

### ISSUE THREAD

**Issue by alvinhochun** [fdehau/tui-rs#372]
**Describe the bug**
On some CJK systems, the default conhost console font treats the box drawing characters as fullwidth, which tends to cause broken layout.

**To Reproduce**
1. Prepare a CJK Windows setup.
2. Run the `crossterm_demo` example.

If using a non-CJK Windows (e.g. the official [development VMs](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/), It can be changed to Traditional Chinese using these steps:
1. Install "Chinese (Taiwan)" or "Chinese (Hong Kong)" UI language in Windows Settings and switch to it.
2. (Unsure if needed:) In the old control panel applet (`intl.cpl`), change the non-unicode display language to "Chinese (Traditional, Taiwan)" and do *not* check the UTF-8 checkbox, then reboot the system.
3. Start `cmd.exe`. It should now show Chinese text with the MingLiU (細明體) font.
    ![TC console in MingLiU](https://user-images.githubusercontent.com/2397650/92598114-f4ad1e80-f2da-11ea-80d6-35718bfa6ecf.png)

**Expected behavior**
Demo should show normally.

**Screenshots**
Screenshot of demo:
![demo](https://user-images.githubusercontent.com/2397650/92597249-b2371200-f2d9-11ea-84f3-0c2df5ce3cbe.png)

Selecting a single char of the sparkline:
![selecting single char](https://user-images.githubusercontent.com/2397650/92597527-1954c680-f2da-11ea-9def-bef63f174a5c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 with Chinese (Hong Kong) interface language
 - Terminal Emulator: Conhost (built-in console)
 - Font: MingLiU (細明體) (default)
 - Crate version: 0.10, master
 - Backend: crossterm

**Additional context**

The box drawing characters and some other characters are ["East Asian Ambiguous"](https://unicode.org/reports/tr11-2/). In the case of CJK Windows, Conhost probably treats them as fullwidth for legacy compatibility reasons.

**Comment by fdehau** [comment]
How does the demo look like when you run it with `--enhanced-graphics false` ?

**Comment by alvinhochun** [comment]
It's not that much different:
![`--enhanced-graphics false`](https://user-images.githubusercontent.com/2397650/93712469-ac1e1c80-fb88-11ea-8423-0b403e3d6cee.png)

**Comment by fdehau** [comment]
Ok so if all characters of this range are rendered this way with this font I think the only solution would be to provide an alternative set of characters to draw those widgets. Given that you seem to have look into this subject a bit already, would you have a suggestion ?

**Comment by alvinhochun** [comment]
If you would add more alternative symbols: The box drawing chars (Block) can be replaced with plain old ASCII `|`, `-` and `+`. The chart can perhaps try U+00B7 `·` instead.

Unfortunately, I don't think there are any alternative chars for the sparkline/bar charts. An alternative would be to fill background colour instead of using the block chars, but this gives an extremely limited resolution. A more radical change would be to add an option to force all ambiguous width chars to be treated as 2-wide, and adapt the sparkline/bar charts to work with that, but this loses half of the x-axis range and probably will take quite some effort to implement.

BTW, the ambiguous chars actually affect more than the drawing chars. Check the screenshots - the Euro sign on the last row is rendered as full width because it is also East Asian ambiguous. If `tui-rs` does any text measurements it might also need an option to account for these differences.
