### ISSUE TITLE
seems like new style diff code broke Cell:set_style

### ISSUE THREAD

**Issue by pm100** [fdehau/tui-rs#378]
If I have rendered some content with say Bold and Blue. And then render more output to that same buffer and overwrite a Blue Bold cell with a a Style::default string, then rather than resetting the style of that cell to default (ie 'plain') it does nothing

```
    pub fn set_style(&mut self, style: Style) -> &mut Cell {
        if let Some(c) = style.fg {
            self.fg = c;
        }
        if let Some(c) = style.bg {
            self.bg = c;
        }
        self.modifier.insert(style.add_modifier);
        self.modifier.remove(style.sub_modifier);
        self
    }
```

because the style is basically empty. In prior design (with modifier() fn rather than add / sub modifier) this would have reset the Cell to 'plain'.

Call chain is buffer::set_string, buffer::set_stringn, Cell::set_style. 
In order to make this work now I have to create a Cell with a style that subtracts the old values , this means I have to keep track of the old style.

**Comment by pm100** [comment]
OK I worked out how to get around this but still fells like a serious break

changed
```
        buf.set_string(
            area.width - small_files_len - 1,
            status_line_y,
            small_files_legend,
            Style::default()
        );
```
to
```
        buf.set_string(
            area.width - small_files_len - 1,
            status_line_y,
            small_files_legend,
            Style::default().fg(Color::Reset).bg(Color::Reset).remove_modifier(Modifier::all())
        );
```

This code is overwriting part of another string that was loaded into the buffer earlier

**Comment by fdehau** [comment]
That's sounds like a bug in the diffing logic when we write to the terminal. Could you create a proper bug report following the template and provide the code of a minimal example triggering this behavior ?

**Comment by pm100** [comment]
this code shows it
```
use std::io;
//use termion::raw::IntoRawMode;
use tui::Terminal;
use tui::backend::CrosstermBackend;
use tui::widgets::{Widget, Block, Borders};
use tui::layout::{Layout, Constraint, Direction};
use tui::style::{Color,Style};

fn main() -> Result<(), io::Error> {
    let stdout = io::stdout();//.into_raw_mode()?;
    let backend = CrosstermBackend::new(stdout);
    let mut terminal = Terminal::new(backend)?;
    terminal.clear();
    let buff = terminal.current_buffer_mut();
    buff.set_string(25, 25, "red", Style::default().fg(Color::Red));
// second string that over laps with the first and tries to draw 'plain' un styled text
    buff.set_string(27, 25, "plain", Style::default());
    terminal.draw(|mut f| {
        let size = f.size();
        let block = Block::default()
            .title("Block")
            .borders(Borders::ALL);
        f.render_widget(block, size);


    })?;
    crossterm::event::read();
    Ok(())
}
```

run with 0.09 the output is

![image](https://user-images.githubusercontent.com/489231/93716538-3896f380-fb25-11ea-9a32-a45850d20240.png)


the 'plain' text beats the 'red' where they overlap

using .10

![image](https://user-images.githubusercontent.com/489231/93716511-1a30f800-fb25-11ea-8dda-e7c86e39404a.png)

the red wins where they overlap.

This is because Cell::set_style actually means merge_style now, Style::default is empty so the merge does nothing

**Comment by fdehau** [comment]
Ok I misunderstood your first report then. If you are rewriting to a cell in the same draw call then what you are experiencing is the expected behavior. Previously if the style of a cell was successively set with styles S1, S2, S3, the resulting style of the cell was S3 (i.e the last one called). A direct implication of this behavior was that every time you had some sort of nested element and you wanted it to inherit the style of its parent you had to provide the style of the parent element again. This made the declaration of some `Widget` unnecessarily verbose and not very user-friendly. With the new system, the resulting style is the left to right merge of (S1, S2, S3).

One quality of life improvement in your case could be to provide a `Style::reset()` constructor that gives you the `Style` object you are currently building by hand. WDYT ?

**Comment by pm100** [comment]
I totally got what you changed. In fact in diskonaut (where the bug arose) it was a bug in its code that caused the overlap. That is now fixed. So I dont need a fix.

Yes somehow you need to differentiate between Style= none and Style = dontcare. So having reset() meaning none and default meaning 'dont care' is good. Doc it tho. 

Although I wonder about the other way round. In 9 default = None, maybe thats how it should stay and have ::new = dont care. Tough call. Either way people will be unhappy. Depends on how far people have got with migrating 9->10. I know other project still stuck on 9 (gitui for example).

The main thing  tho is to doc it
