### ISSUE TITLE
Missing last character when wrapping text

### ISSUE THREAD

**Issue by maitesin** [fdehau/tui-rs#38]
I noticed in the demo application the footer section does not show the last character of the line before being wrapped. I tried adding a `margin`, but didn't fix it.

**Comment by holmgr** [comment]
Having the same issues, found any decent way of fixing the problem @maitesin ? Thinking about manually inserting newline characters but it would be nice if I could avoid it.

**Comment by maitesin** [comment]
I haven't had time to look into it much further :( @holmgr . The only problem of adding the newline characters is that you won't benefit from the wrapping of text.
