### ISSUE TITLE
Moving between different displays causes the title of the first block to be corrupted

### ISSUE THREAD

**Issue by theWebalyst** [fdehau/tui-rs#382]
**Describe the bug**
I'm using left and right arrow keys to move between different renderings, one with several blocks of stateful lists (display A) and one with just one block showing a stateful list (display B).

The top left block in display A and the block in display B have titles "Vault Status" and "Debug Window" respectively. 

Screenshot vdash 1: I begin with display A which renders the title as expected (i.e. the top left of the terminal window has a corner character followed by the text "Vault Status").
![vdash 1](https://user-images.githubusercontent.com/2183895/93713753-ed490900-fb55-11ea-8137-1270e3ac7e07.png)

I press right arrow to switch the display from A to B:

Screenshot vdash 2: The title of the debug window in display B shown incorrectly. Instead of corner-character followed by "Debug Window" the text becomes "Debugt Window" with the "D" overwriting the corner-character. 
![vdash 2](https://user-images.githubusercontent.com/2183895/93713755-f043f980-fb55-11ea-8ff3-e95cf0f4bec1.png)

I press the right (or left) arrow to move from display B back to display A.

Screenshot vdash 3: Display A now shows the top left block with a corrupted title "Vaultt Status" (with a doubt 't') and also begins where the corner character should be.

My app builds with either crossterm and termion backends and both show this effect.
![vdash 3](https://user-images.githubusercontent.com/2183895/93713757-f33eea00-fb55-11ea-960e-2585d52e3f70.png)

**To Reproduce**
Let me know if you want more on this either by building my app ([vdash](https://github.com/theWebalyst/vdash)) or in some other way.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - xterm
 - default
 - tui-rs version: 0.10.0
 - Backend: termion or crossterm

**Extra Info**

**Note 1:** the window shown in bottom right of display A with title "Debug Window" is the same block which makes up the whole of display B. When shown on display A, the title of "Debug Window" always displays correctly.

**Note 2:** I've tested this using other characters to navigate (e.g. 'x') and the effect is the same, so it doesn't appear to be caused by some other processing of the input, but I can't be sure.

**Note 3:** I'm using tokio futures to handle two streams of input, one for events closely based on the termion and crossterm examples, and another future receiving updates from a file watcher. The latter is not active while this is happening.

The app is easy to build and run, instructions here: [vdash](https://github.com/theWebalyst/vdash)

**Comment by fdehau** [comment]
I've just released a new version that might contain a fix for this. Could you try to upgrade to 0.11.0 ?

**Comment by theWebalyst** [comment]
Man, fixing bugs before I report them is seriously good practice :clap:

Thank you, all working now.
