### ISSUE TITLE
If chart elements and the legend overlap, it causes the legend to have strangely coloured edges.

### ISSUE THREAD

**Issue by ClementTsang** [fdehau/tui-rs#387]
**Describe the bug**
It seems like if a chart element is being drawn under the legend, it ends up causing parts of the legend's box to have those chart's colours.

**To Reproduce**
I'm assuming that this will occur anytime you have a chart where the drawn points overlap the legend.

**Expected behavior**
I would expect the legend would not have these weird colours.

**Screenshots**

![image](https://user-images.githubusercontent.com/34804052/94351847-2a1c7080-002c-11eb-9af6-57fb1a063ce1.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Terminal Emulator: Kitty, can also reproduce on urxvt
 - Font: IBM Plex Mono
 - Crate version: 0.11.0
 - Backend: crossterm

**Additional context**
This did not occur on 0.9, so I'm assuming this bug started occurring in either 0.10 or 0.11 (I jumped directly to 0.11).

**Comment by ClementTsang** [comment]
Seems like a really easy way to bandaid it is to just forcefully set a border style when drawing the Block for the legend?

So in `chart.rs`, instead of:

```rs
        if let Some(legend_area) = layout.legend_area {
            Block::default()
                .borders(Borders::ALL)
                .render(legend_area, buf);
            //...
        }
```

do

```rs
        if let Some(legend_area) = layout.legend_area {
            Block::default()
                .borders(Borders::ALL)
                .border_style(Style::default().fg(Color::Reset))
                .render(legend_area, buf);
            //...
        }
```

It seems to fix my issue at the very least, though idk if you want to fix it like that.

**Comment by fdehau** [comment]
Thanks for the detailed bug report. I may have a solution in #388. Rather than forcing a border style, I think I got to the root cause of the issue which was that the style was not properly restored to the widget style for all components drawn on top of the graph area (ie legend and axis titles). I also added a test to avoid a future regression. Could you try it out and confirm this fixes your issue ?

**Comment by ClementTsang** [comment]
Just tried it, seems to work great!  Thanks for getting back to me quickly on this.
