### ISSUE TITLE
[help] How to "select" a block and then focus navigation on that block?

### ISSUE THREAD

**Issue by yatesco** [fdehau/tui-rs#411]
Hi there (newbie warning),

I want to `tab` between blocks and have the focus enter that block, so `Up` and `Down` scroll the list in that block (for example).

Is this something I need to track myself or is there an abstraction within `tui-rs` that enables this?

Thanks!

**Comment by fdehau** [comment]
There is no abstraction in `tui` that would allow you to solve this out of the box but this should be pretty easy to implement yourself. There are many ways to do this and you may take some inspiration from the tabs in [the demo](https://github.com/fdehau/tui-rs/blob/25ff2e5e61f8902101e485743992db2412f77aad/examples/util/mod.rs#L58).

Feel free to reopen if you want further details :)
