### ISSUE TITLE
Implementing Page Down on lists

### ISSUE THREAD

**Issue by ThomWright** [fdehau/tui-rs#412]
Hi,

I'm trying to implement handling the Page Up and Page Down keys on a list. I want to mimic the same behaviour I see elsewhere, which as far as I can see is to move the 'cursor' (list item selection in this case) up or down by one 'page' (visible list height in this case).

The trouble I'm having is finding a nice way to figure out the list height in order to know how far up or down to move my selection.

Here is my solution to getting the list height, which works, but means I end up repeating the layout logic outside of my `draw` function. I feel like I'm misusing the APIs here, and doing something I shouldn't. I'm also having to use a mutable reference in order to get the frame to get the size which doesn't feel right.

This example is obviously missing some context, but I'm hoping makes basic sense on its own. I'm happy to flesh it out if it helps illustrate the solution better.

```rust
  pub fn list_height(&mut self) -> u16 {
    let frame = self.terminal.get_frame();
    let frame_chunks = self.frame_layout.split(frame.size());
    let files_block = files_block(); // 
    let files_block_inner_area = files_block.inner(frame_chunks[0]);
    let list_chunks = self.list_layout.split(files_block_inner_area);
    list_chunks[0].height
  }
```

Essentially, I'm not very happy with it, and I'm wondering if either:

1. there's a better solution, or
2. there are some changes in `tui` which could be made to make this easier.

Thanks for any help.

**Comment by philippeitis** [comment]
The solution seems to be to get the list height in the draw call itself / store it as a variable?

In your specific example, I'd do the following:

```
pub struct UiState {
    lists: [ListState; 2],
    list_height: Option<u16>
}

...
impl<B: Backend> Ui<B> {
    pub fn draw(
        &mut self,
        state: &app::State,
        ui_state: &mut UiState,
    ) -> io::Result<()> {
        let frame_layout = self.frame_layout.clone();
        let list_layout = self.list_layout.clone();

        self.terminal.draw(|f| {
            let frame_chunks = frame_layout.split(f.size());

            let files_block = files_block();
            let files_block_inner_area = files_block.inner(frame_chunks[0]);
            f.render_widget(files_block, frame_chunks[0]);

            {
                let list_chunks = list_layout.split(files_block_inner_area);
                self.list_height = Some(list_chunks[0].height);
                Ui::draw_file_list(
                    f,
                    list_chunks[0],
                    &state,
                    &mut ui_state.lists[0],
                    0,
                );
                Ui::draw_file_list(
                    f,
                    list_chunks[1],
                    &state,
                    &mut ui_state.lists[1],
                    1,
                );
            }

            Ui::draw_status(f, frame_chunks[1], &state);
        })
    }
}
```

**Comment by ThomWright** [comment]
That's a good solution, I'll give that a try, thanks!
