### ISSUE TITLE
RFC: Table widget redesign

### ISSUE THREAD

**Issue by fdehau** [fdehau/tui-rs#418]
I've been working on a new design for the `Table` widget given the obvious shortcomings of the original version. Several users have complained that they are not able to use the widget as they intend to:
- Cannot apply a style to an entire header: https://github.com/fdehau/tui-rs/issues/401
- Cannot apply a style to the entire row: https://github.com/fdehau/tui-rs/pull/365
- Cannot have columns with different styles: https://github.com/fdehau/tui-rs/issues/330
- Table panics on small areas: https://github.com/fdehau/tui-rs/issues/314
- Support headerless table without an header gap: https://github.com/fdehau/tui-rs/pull/310
- Incremental styling: https://github.com/fdehau/tui-rs/pull/317
- Inconsistent margins: https://github.com/fdehau/tui-rs/issues/299

To address these issues, the new design will leverage the [new text primitives](https://github.com/fdehau/tui-rs/pull/316) and take inspiration of the `List` latest changes. The new `Table` will have the following features:
* Full support for rows spanning over multiple lines. Each `Row` can have its own style.
* A `Row` is composed of `Cell`s. Each `Cell` can have its own style and you have full control over the style of the content because it is represented using a `Text`.
* Margins are no longer off when a row is selected.
* The table no longer panics on small areas and the width of the columns correctly account for the space allocated between each column.
* The header is optional and is simply a `Row` that is always visible and cannot be selected.

You can see a [WIP implementation here](https://github.com/fdehau/tui-rs/pull/417).

**Comment by leebenson** [comment]
Awesome, thanks @fdehau - looking forward to trying out these improvements when ready.

FYI, we're using TUI in Vector @ https://vector.dev, for our new CLI observability tool. Love it!

**Comment by fdehau** [comment]
@leebenson Super stoked to see `tui` used in `vector` :). I've merged the new implementation of `Table` and it should be part of the next release.
