### ISSUE TITLE
Question: is it possible to remotely update the content inside of a Paragraph?

### ISSUE THREAD

**Issue by ReagentX** [fdehau/tui-rs#419]
If I have access to a `Terminal` that contains a `Paragraph`, is the only way to update the `Text` in a `Paragraph` to tear down the old one and replace it with a new one? I don't see any obvious update methods on either `Text` or `Paragraph`.

**Comment by fdehau** [comment]
`tui` provides an immediate mode API. All widgets that are part of the UI are supposed to be built from scratch at each draw call. Therefore, when the text you want to print to the terminal changes, you simply have to construct a new Paragraph with its value and the crate will take care of the rest (i.e emitting the minimal number of ANSI escapes sequences required to update the terminal).

For example, let's say you want to have a text that changes every second:
```rust
    // Our state
    let mut i = 0;
    loop {
        terminal.draw(|f| {
            // The UI text is derived from our state
            let text = if i & 1 == 0 {
                format!("{} is even", i)
            } else {
                format!("{} is odd", i)
            };
            let paragraph = Paragraph::new(text);
            // register the widget for this draw call
            f.render_widget(paragraph, f.size());
        })?;
        // Update our state
        i += 1;
        thread::sleep(Duration::from_secs(1));
    }

```
