### ISSUE TITLE
Layout.split is not stable; returns different dimensions depending on how often it is called

### ISSUE THREAD

**Issue by ReagentX** [fdehau/tui-rs#420]
**Describe the bug**
Calling Layout.split does not have predictable results.

**To Reproduce**

```rust
    use std::error::Error;
    use std::io::{stdout, Write};
    use tui::Terminal;
    use tui::{
        backend::{Backend, CrosstermBackend},
        layout::{Constraint, Layout, Rect},
        style::{Color, Style},
        text::{Span, Spans},
        widgets::{Block, Borders, Paragraph},
        Frame,
    };
    use crossterm::{
        event::EnableMouseCapture,
        execute,
        terminal::{enable_raw_mode, EnterAlternateScreen},
    };
    fn main() {
        build();
    }

    pub fn build() -> Result<Terminal<CrosstermBackend<std::io::Stdout>>, Box<dyn Error>> {
        // Initial setup
        enable_raw_mode()?;
        let mut stdout = stdout();
        execute!(stdout, EnterAlternateScreen, EnableMouseCapture);
        let backend = CrosstermBackend::new(stdout);
        let mut terminal = Terminal::new(backend).unwrap();
        terminal.draw(|f| draw_initial(f))?;
        loop {}
        // return Ok(terminal);
    }

    pub fn draw_initial<B: Backend>(f: &mut Frame<B>) {
        let size = f.size();
        let chunks = Layout::default()
            .constraints([Constraint::Min(2), Constraint::Min(2)].as_ref())
            .split(Rect {
                x: 0,
                y: 0,
                width: size.width,
                height: size.height - 3,
            });
        let text = "I\nam\na\ncontent\nline";
        let content = Paragraph::new(Spans::from(Span::styled(
            text,
            Style::default().fg(Color::Red),
        )));
        f.render_widget(content, chunks[0]);
        let text2 = "command line";
        let content2 = Paragraph::new(Spans::from(Span::styled(
            text2,
            Style::default().fg(Color::Red),
        )))
        .block(
            Block::default()
                .borders(Borders::TOP)
                .title("──Command Line"),
        );
        f.render_widget(content2, chunks[1]);
        println!("{:?}", chunks);
    }
```

**Expected behavior**
The same layout is always generated.

**Screenshots**
The layout is different sometimes (third pane). The darker gray lines are the pane separators in `tmux`.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/1920666/99582007-7f7f5900-29af-11eb-9742-e3fa2d1efb9e.png">

Same problem in 4 separate iTerm 2 windows; the second terminal is rendered differently:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/1920666/99583539-a63e8f00-29b1-11eb-805b-7f243ee00e91.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.0.1 (20B29)
 - Terminal Emulator: iTerm2, Alacritty
 - Font: Fira Code
 - Crate version: `tui = { version = "0.13", default-features = false, features = ['crossterm'] }`
 - Backend: `crossterm = "0.18"`

**Comment by fdehau** [comment]
This crate uses `cassowary-rs` to find a layout solving the provided constraints. When the constraints are ambiguous or multiple solutions can satisfy them, the crate documentation suggest that:

> for efficiency reasons this is picked nondeterministically

In your case, both layouts are actually valid solutions to your constraints, so I would advise you to use more precise constraints. At some point we may replace the underlying layout system but this is definitely not a priority at the moment :).
