### ISSUE TITLE
Can we expose `terminal::previous_buffer()` to read the content on the screen?

### ISSUE THREAD

**Issue by DarrenTsung** [fdehau/tui-rs#436]
Hi, thank you for the great crate.

**Is your feature request related to a problem? Please describe.**
I'm adding mouse event support to my CLI tool - I would like to get the text at the mouse position. I initially thought that `terminal::current_buffer_mut()` would be useful, however after a `.draw()` call, the current buffer refers to the reset buffer.

If I had a reference to the other buffer with state from the `.draw()` call, it would be easy to get the symbol at the cursor position:
```
// terminal.draw(..);
// ...

Event::Mouse(mouse_event) => match mouse_event {
    MouseEvent::Press(MouseButton::Left, x, y) => {
        let buffer = terminal.previous_buffer();
        let index = x + (y * buffer.area.width);
        let cell = &buffer.content[index as usize];
        let symbol = cell.symbol.trim();
    }
}
```

It would be bad for the user to mutate this buffer, so we could expose a read-only reference.

**Describe the solution you'd like**
`Terminal` exposes a read-only reference to the previous buffer (which contains the cell state after a `.draw()`) via a public method.

**Additional context**
I'm able to hack my way around this by cloning the `current_buffer_mut()` before the draw call and rendering the widgets into it directly.

```
// HACK: capture the buffer only if we want to read from it after drawing.
let mut buffer = if let Event::Mouse(MouseEvent::Press(MouseButton::Left, _, _)) = event
{
    Some(terminal.current_buffer_mut().clone())
} else {
    None
};

terminal.draw(|f| {
     // ..
    let widget = ..;
    if let Some(buffer) = buffer.as_mut() {
        widget.clone().render(chunks[0], buffer);
    }
    f.render_widget(widget, chunks[0]);
});

if let Event::Mouse(MouseEvent::Press(MouseButton::Left, _, _)) = event {
    // read symbol from buffer, everything works as expected
}
```

Obviously this is not ideal since it clones the widget and renders it twice.

**Comment by fdehau** [comment]
Thanks for the detailed report. This seems like a valid feature request and as you rightfully exposed probably mandatory if you wish to get the terminal content as soon as you handle the mouse events yourself. Let me know if the changes in #440 would fit your use case.

**Comment by DarrenTsung** [comment]
Those changes look good 👍🏻  and would work for my use-case!
