### ISSUE TITLE
move util from examples to crate?

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [fdehau/tui-rs#437]
**Is your feature request related to a problem? Please describe.**
It seems that the util module from the examples folder is quite useful. If so, then why hasn't it been moved to the crate?

**Describe the solution you'd like**
You could implement a seperate util section in the crate, tui::util. 

**Describe alternatives you've considered**
Or move the useful parts of util into there own sections. 
tui::Event, tui::Events.

**Additional context**
It just striked me as odd that this wasn't in the main crate. Instead of having to copy the util module to the project, just have it in the tui crate.

**Comment by fdehau** [comment]
I don't see anything in `util` that might be useful in the crate itself:
* The event handling part works only with `termion`. Moreover, I think one strong point of this crate is that we don't force a particular event handling on the users so they are totally free to call `tui` when they see fit. Promoting and supporting an half baked solution does not align well with this objective in my opinion. We might provide abstraction for the input handling at some point to ease the switch between backends though.
* The rest is mainly some common types used in several examples but they are unlikely to be useful to users of the crate.

So for now I'm not planning to move functionalities from `util` to the main crate.

**Comment by chromafunk** [comment]
Hi, I'm new to Rust and I need to run an example to start getting to know the library, but when I add  tui as a dependency as described in the documentation and try to run  an example, I get `file not found for module `util``. What can I do to make this work ? Do I need to manually download the util directory and place it somehow somewhere so I can use it ?
