### ISSUE TITLE
Support vector constraints for the Table widget

### ISSUE THREAD

**Issue by jesseduffield** [fdehau/tui-rs#442]
**Is your feature request related to a problem? Please describe.**
I want to render a table with a dynamic number of columns that can't be known at compile time, but the `widths` function on the Table widget expects a Constraint array rather than a vector.

**Describe the solution you'd like**
I'd like to be able to pass a vector of constraints rather than an array.

**Describe alternatives you've considered**
None.

**Additional context**
I am very, very new to rust so I hope this all makes sense

**Comment by fdehau** [comment]
I'm not sure to understand the issue. `Table::widths` expect a slice ref. If you have `Vec<Constraint>` it should be possible to give it as argument to `Table::widths` directly. Do you have an example of code that would reproduce your issue ?

**Comment by jesseduffield** [comment]
My bad, looks like I just needed to use a turbofish when calling `collect` to specify it was a `Vec<Constraint>`. Apologies for the false alarm!
