### ISSUE TITLE
More Method Level Documentation

### ISSUE THREAD

**Issue by TheMayoras** [fdehau/tui-rs#444]
**Is your feature request related to a problem? Please describe.**
For someone new to tui, some of the methods lack documentation which makes it difficult to find the methods to I needed.
For example, it is not clear what the method `tui::widgets::Paragraph::scroll` does.

**Describe the solution you'd like**
More documentation on methods (widgets specifically).  Methods like `tui::widgets::Paragraph::scroll` and `tui::widgets::List::start_corner` should contain documentation with a description of what they do.  

**Describe alternatives you've considered**

**Additional context**

**Comment by fdehau** [comment]
I agree the documentation has a lot of gaps at the moment but this may also be one of the most time consuming and difficult thing to get right in an open source project. If you see things where documentation is missing and/or might be improved feel free to send a PR :).
