### ISSUE TITLE
RE: Is the API going to change in future releases?

### ISSUE THREAD

**Issue by Joe23232** [fdehau/tui-rs#445]
Hi, I wanted to enquire as I believe this is not a stable release, is the API going to change with each update(s)? If so by how much is it going to change?

**Comment by fdehau** [comment]
Hey ! Yes `tui` is not stable and futures releases may contain breaking changes. As I've said in the past and although the crate has been around for quite some time, its recent popularity has triggered a lot of feedback and thus highlighted its shortcomings that would need to be addressed before I can consider it stable. Having said that, I try to make API changes only when they make sense and provide detailed instructions in the CHANGELOG to ease the upgrade process.

I hope this answer your question :).
