### ISSUE TITLE
Some arithmetic overflow bugs found by afl.rs

### ISSUE THREAD

**Issue by StevenJiang1110** [fdehau/tui-rs#446]
I've using [afl.rs](https://github.com/rust-fuzz/afl.rs) to fuzz this crate. And I've found several API may panic due to arithmetic overflow. 

There are four APIs we find may panic. We just download tui.rs from this respository and add it as a dependency to our fuzzing target. The codes to replay this panics are

```rust
let rect1 = tui::layout::Rect::new(12336 ,12336 ,12336 ,12336);
let rect2 = tui::layout::Rect::new(58928 ,12336 ,12336 ,0);
let _ = tui::layout::Rect::union(rect1 ,rect2);
```

```rust
let rect1 = tui::layout::Rect::new(12336 ,12336 ,12336 ,12336);
let rect2 = tui::layout::Rect::new(12336 ,65328 ,12336 ,12336);
let _ = tui::layout::Rect::intersection(rect1 ,rect2);
```

```rust
let rect1 = tui::layout::Rect::new(12336 ,12336 ,12336 ,12336);
let rect2 = tui::layout::Rect::new(57648 ,12336 ,65328 ,48);
let _ = tui::layout::Rect::intersects(rect1 ,rect2);
```

```rust
let rect1 = tui::layout::Rect::new(12336 ,12336 ,12336 ,12336);
let mut buf1 = tui::buffer::Buffer::empty(rect1);
let rect2 = tui::layout::Rect::new(12336 ,12336 ,12336 ,12336);
let buf2 = tui::buffer::Buffer::empty(rect2);
let _ = tui::buffer::Buffer::merge(&mut buf1 ,&buf2);
```

we also put these code on [first](https://github.com/StevenJiang1110/afl_rust_crashes/tree/main/tui/replay_tui-20-3), [second](https://github.com/StevenJiang1110/afl_rust_crashes/tree/main/tui/replay_tui-21-3), [third](https://github.com/StevenJiang1110/afl_rust_crashes/tree/main/tui/replay_tui-22-7),  [fourth](https://github.com/StevenJiang1110/afl_rust_crashes/tree/main/tui/replay_tui-27-9).

The bug report is 
![截屏2021-01-09 下午10 10 58](https://user-images.githubusercontent.com/27764680/104093752-8f3c5f00-52c7-11eb-8566-40f5e7c1cc62.png)

I hope you can check if these are real bugs need to be fixed. Thanks a lot.

**Comment by DarrienG** [comment]
I haven't worked on the project in a bit, but as a point of reference, when we hit a similar problem a long while ago we used saturating adds and subtracts https://github.com/fdehau/tui-rs/pull/283
