### ISSUE TITLE
Scrolling text can cause extra display characters

### ISSUE THREAD

**Issue by brooksmtownsend** [fdehau/tui-rs#447]
**Describe the bug**
I have a vertically scrolling output window to show REPL command output in my program [wash](https://github.com/wasmCloud/wash). As output reaches the bottom of the window the pane automatically scrolls (using a scroll offset), and this often leads to characters being printed repeatedly vertically, seemingly random which ones are selected to be displayed in this way. Please refer to screenshot for the exact behavior.

**To Reproduce**
With my program, you can install via `cargo install --git https://github.com/wasmcloud/wash --branch main --tag v0.1.13`. You will need an instance of [nats-server](https://github.com/nats-io/nats-server) running for the program to work, but this can be easily run in a docker container using `docker run --name nats --network nats --rm -p 4222:4222 -p 8222:8222 nats`.

Run `wash up` to launch the REPL, then you can reproduce this behavior by running `get hosts`, then copying the ed25519 key and using it as an argument to `get inventory` repeatedly until the output scrolls. Then, you can hold SHIFT and use UP/DOWN on the arrow keys to scroll, and you should see some repeated characters across the screen. Refer to screenshot for this example.

For a more complicated example, I find that the more complicated the output is the more likely it is to corrupt. You can see this in the second screenshot. Here is the list of commands that you can copy/paste into the REPL to get more complicated output.
```
start actor wascc.azurecr.io/kvcounter:v0.1.1
start provider wascc.azurecr.io/redis:v0.9.2 -t 30
link MC6Z57M3HOUPIAMTZDMKFBJ5AZ3UOWZ4WJYO7DZNA6567XSJNBUQP55I VAZVC4RX54J2NVCMCW7BPCAHGGG5XZXDBXFUMDUXGESTMQEJLC3YVZWB wascc:keyvalue URL=redis://localhost:6379
start provider wascc.azurecr.io/httpsrv:v0.9.2 -t 30
link MC6Z57M3HOUPIAMTZDMKFBJ5AZ3UOWZ4WJYO7DZNA6567XSJNBUQP55I VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M wascc:http_server PORT=8080
call MC6Z57M3HOUPIAMTZDMKFBJ5AZ3UOWZ4WJYO7DZNA6567XSJNBUQP55I HandleRequest {"method": "GET", "path": "/mycounter", "body": "", "queryString":"", "header":{}}
get hosts
get inventory <fill in your host here>
```

(edit): My code specific to this output panel is here: https://github.com/wasmCloud/wash/blob/main/src/up.rs#L717

**Expected behavior**
I expect for output to be the same whether or not I put it into a pane that has a scroll offset, and I'd expect for characters to not print duplicates vertically across the window.

**Screenshots**
![image](https://user-images.githubusercontent.com/12040685/104203984-bf384f00-53fa-11eb-90d9-8f5b5cc854dc.png)
![image](https://user-images.githubusercontent.com/12040685/104204279-1807e780-53fb-11eb-89d0-9e1ed35184b2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux,Windows]
 - Terminal Emulator [e.g xterm, Konsole, Terminal, iTerm2, ConEmu]
 - Font [e.g Inconsolata, Monospace]
 - Crate version [e.g. 0.7]
 - Backend [e.g termion, crossterm]

**Additional context**
In my `Cargo.toml`, here are my dependency versions & feature flags:
```
tui = { version = "0.12.0", default-features = false, features = ["crossterm"] }
```
I use `0.12.0` as another crate that I use, `tui-logger` depends on that version of `tui`.

**Comment by brooksmtownsend** [comment]
Any updates here?

**Comment by fdehau** [comment]
Hey ! Thanks for the detailed bug report. I'm afraid I don't have the time to reproduce your issue with your suggested steps but I took a quick look at your code. In order to exclude any obvious problems first, could you:
1. Dump the string given as an input to the `Paragraph` widget and check the artifacts are not already there.
2. Check whether your output can contain unusual utf-8 graphemes.
3. Fill the missing information about the environment you are running your app in.

**Comment by brooksmtownsend** [comment]
Thanks @fdehau !
1. Dumping the string given to the `Paragraph` widget shows that the artifacts are not present there, which is good to know
2. Since the output consists of standard utf-8 characters, and the only output that makes it to the paragraph is via the `chars()` iterator (https://doc.rust-lang.org/std/string/struct.String.html#method.chars) I am fairly confident that there aren't any non-standard characters making it into the output.
3. Apologies, I thought that I filled this out previously
4. Desktop (please complete the following information):
OS: [e.g. Linux,Windows]: MacOS
Terminal Emulator [e.g xterm, Konsole, Terminal, iTerm2, ConEmu]: Alacritty / VSCode integrated terminal (with tmux)
Font [e.g Inconsolata, Monospace]: Menlo Regular Monospace
Crate version [e.g. 0.7]: `0.14.0`
Backend [e.g termion, crossterm]: termion `1.5`, I've also observed this with crossterm `0.19.0`

It's worth mentioning that it seems to happen consistently before some whitespace (see screenshot for example). You can see that it happens to "Host", and the IDs (scrolling down). I'll do a bit more investigation to see if I can figure out why that's the case, but if you have any further debugging steps please let me know 😃 
<img width="751" alt="Screen Shot 2021-02-22 at 9 02 54 AM" src="https://user-images.githubusercontent.com/12040685/108718733-c15af680-74ec-11eb-8a12-9852dc45a354.png">

**Comment by brooksmtownsend** [comment]
@fdehau Investigating this again, turns out you were right, it was null characters in the table border! https://docs.rs/term-table/1.3.1/src/term_table/lib.rs.html#262-276

Closing this as replacing the `\0` characters with a single space works just fine 👍🏻

**Comment by medwards** [comment]
How did you dump the output? I am having similar issues with a `Paragraph`.

**Comment by brooksmtownsend** [comment]
@medwards in my code I also make use of https://github.com/gin66/tui-logger, so I just threw the contents of the paragraph into an `info!` log and inspected it there. Are you using term_table as well?

**Comment by medwards** [comment]
Nope, but I figured the technique you used for debugging would work for me too. Thanks for pointing me to `tui-logger`
