### ISSUE TITLE
Question: Set the title to the top right or middle of a block.

### ISSUE THREAD

**Issue by KallenW** [fdehau/tui-rs#450]
I didn't find the relevant API in the documentation. Maybe I should implement a custom widget ?

**Comment by fdehau** [comment]
This is not supported at the moment but should be fairly easy to implement, e.g adding a `title_alignment` to `Block` and change the logic [here](https://github.com/fdehau/tui-rs/blob/4e76bfa2ca8eb51719d611bb8d3d4094ab8ba398/src/widgets/block.rs#L195) to handle this new property.

I might have the time to address it in a future release but in the meantime I'll leave it as a good first issue if anyone want to pick it up.

**Comment by olitus** [comment]
Hello, I am kinda newbie in Rust and would like to implement this. 
This would be my first contribution to Open Source project, so I am very excited.
Thank you for pointing to the correct parts of code.

**Comment by olitus** [comment]
Here is my pull request https://github.com/fdehau/tui-rs/pull/462

**Comment by oreksu** [comment]
Should we close this issue?
