### ISSUE TITLE
How to implement a resizable terminal?

### ISSUE THREAD

**Issue by actuday6418** [fdehau/tui-rs#451]
Is the following code snippet supposed to create a resizable application? It doesn't resize itself on my terminal (Plasma Konsole), but the example applications do. I grep'd through the example code and didn't find any explicit calls to `terminal.resize(terminal.size()?)`, so I assume the resizing must be automatic. Any idea why it doesn't work for me?

```
use std::io;
use termion::{
    event::Key, input::MouseTerminal, input::TermRead, raw::IntoRawMode, screen::AlternateScreen,
};
use tui::{
    backend::TermionBackend,
    //layout::{Constraint, Layout},
    style::{Color, Style},
    text::Span,
    widgets::{Block, BorderType, Borders},
    Terminal,
};

fn main() {
    // Terminal initialization
    let stdout = io::stdout().into_raw_mode().unwrap();
    let stdout = MouseTerminal::from(stdout);
    let stdout = AlternateScreen::from(stdout);
    let backend = TermionBackend::new(stdout);
    let mut terminal = Terminal::new(backend).unwrap();

    'main: loop {
        terminal
            .draw(|f| {
                let block = Block::default()
                    .border_style(Style::default().fg(Color::Green))
                    .borders(Borders::ALL)
                    .title(Span::styled(
                        "Gremlin",
                        Style::default().fg(Color::LightCyan),
                    ))
                    .border_type(BorderType::Rounded);
                f.render_widget(block.clone(), f.size());
            })
            .unwrap();
        for c in io::stdin().keys() {
            match c.unwrap() {
                Key::Ctrl('c') => break 'main,
                _ => {}
            }
        }
    }
}
```

I tried calling the resize method explicitly on a key press as well, but this just makes the whole screen go blank. I can provide a screen recording if necessary.

**Comment by qiujiangkun** [comment]
You need two things:
```rust
terminal.autoresize()?;
```
and optionally`async` stdin

**Comment by actuday6418** [comment]
Thanks for the reply @qiujiangkun. My issue was fixed after I removed the for loop handling user input and replacing it with code running in another thread. Doing this fixed the resizing issue and an issue where my paragraphs couldn't be scrolled. 

I don't think `terminal.autoresize()?` is necessary as my code works without it, and the paragraph.rs example does too.
