### ISSUE TITLE
Any support for async?

### ISSUE THREAD

**Issue by iptq** [fdehau/tui-rs#460]
I'm writing an application which consists of multiple asynchronous pieces. For the UI part, I'm running `tui` under a `tokio::task::LocalSet`, which can run futures that are not `Send`. However, `tui::Terminal` doesn't seem to expose any async APIs that let me actually take advantage of the async IO of the underlying library ([crossterm async stdout example][1]).

Theoretically, would tui be able to operate under a thread-local async context? How complex would this be to implement?

[1]: https://github.com/crossterm-rs/crossterm/blob/a9d9aff3f0397643be6f834f3f2777f6d8d996e9/examples/event-stream-tokio.rs

**Comment by iptq** [comment]
actually on closer inspection the crossterm example doesn't actually make use of AsyncWrite

**Comment by AlbanMinassian** [comment]
Read <https://monkeypatch.io/blog/2021/2021-05-31-rust-tui/>

**Comment by ciphergoth** [comment]
Looks like they broke their URLs; the new URL is https://www.monkeypatch.io/blog/2021-05-31-rust-tui
