### ISSUE TITLE
backend `get_cursor()` is 2 seconds slow when benchmarking

### ISSUE THREAD

**Issue by grtcdr** [fdehau/tui-rs#468]
**Describe the bug**
I have a program that I usually benchmark before every release to let users know how performance is evolving, and after a recent update, which started utilizing tui-rs and crossterm as a backend, benchmarking the program (using hyperfine) results in very big and inaccurate numbers, there's always a 2 second delay and one of our users has made it obvious through screenshots that `tui::backend::Backend::get_cursor()` is the culprit.

`tui::backend::Backend::get_cursor()` isn't actually "slow" when running the program normally, but benchmarking it always results in a number around 2 seconds.

**To Reproduce**
Benchmark a static program that utilizes tui-rs, Macchina (system information fetcher) for example.
- `hyperfine -w 5 "macchina"`

**Expected behavior**
Accurate performance statistics.

**Screenshots**
Screenshots are provided in @uttarayan21's comment.

**Desktop**
 - OS: Linux
 - Terminal Emulator: Kitty
 - Font: JetBrains Mono
 - Crate version: 0.14.0
 - Backend: Crossterm

**Comment by uttarayan21** [comment]
Okay so I did a bit more testing and it is the **backend.get_cursor()** function and **not** the backend.draw() function that's responsible for this.
![get_cursor](https://user-images.githubusercontent.com/18732700/114909058-5bc71e80-9e3a-11eb-93e2-8e7f067f22cc.png)

![maccina_log](https://user-images.githubusercontent.com/18732700/114909068-5ec20f00-9e3a-11eb-8560-a491e1d3d44a.png)

minimal repoducible 
```rust
use tui::backend::{Backend, CrosstermBackend};
fn main() {
    let mut backend = CrosstermBackend::new(std::io::stdout());
    backend.get_cursor().unwrap();
    println!("Hello, world!");
}
```
This takes around 2 seconds to panic on hyperfine.

**Comment by grtcdr** [comment]
We were able to fix benchmarking by checking if the stream is stdout (using atty crate) before calling get_cursor().
