### ISSUE TITLE
Clear Widget does not work on Crossterm and Windows Terminal

### ISSUE THREAD

**Issue by zombiepigdragon** [fdehau/tui-rs#476]
## Description

The [Clear](https://docs.rs/tui/0.15.0/tui/widgets/struct.Clear.html) widget should clear the screen with the area. Instead, it seems to have no effect.

## To Reproduce

An example that reproduces this behavior:
```rust
use std::{io, thread, time::Duration};

use tui::{Terminal, backend::CrosstermBackend, widgets::{Block, Borders, Clear}};

fn main() -> Result<(), io::Error> {
    // Fill the screen with nonsense
    println!("{}", "bootsandcatsand".repeat(1000));

    // Create the terminal
    let stdout = io::stdout();
    let backend = CrosstermBackend::new(stdout);
    let mut terminal = Terminal::new(backend)?;

    // Put everything on the screen
    terminal.draw(|f| {
        let area = f.size();
        let block = Block::default()
        .borders(Borders::ALL)
        .title("Empty box");
        // Clear the screen (This does not work)
        f.render_widget(Clear, area);
        // Draw the block
        f.render_widget(block, area);
    })?;

    // Pause for good measure
    thread::sleep(Duration::from_secs(5));

    Ok(())
}
```

## Expected behavior

I expect the area (in this case, the full screen) to be cleared before the block is printed, rather than leaving the text on screen. In addition, I expect the spaces in the block's title to be displayed as such rather than showing the previous character.

## Screenshots

The example above:
![image](https://user-images.githubusercontent.com/26581798/116893008-15254280-abf6-11eb-9855-a8f9f8e4f4d3.png)

## Environment

- OS: Windows 10
- Terminal Emulator: Windows Terminal
- Font: Cascadia Code
- Crate version: `0.15.0`
- Backend: crossterm `0.19.0`

## Additional context

There is a chance there is an bug with crossterm that is causing this, but I have not attempted to troubleshoot using crossterm without the tui-rs wrapper. In addition, in my experimentation I found that by trying to draw the block before clearing, I end up not having a visible block, but also not having a visible break in the noise being printed to the screen.

**Comment by extrawurst** [comment]
this is no bug at all and expected behaviour sine you *fill the buffer* not using `tui`. `tui` keeps an internal buffer of the terminal and only sends diffs to the `backend`, since you manually go around that via `printf` the clear call thinks it cleared everything

**Comment by fdehau** [comment]
As @extrawurst pointed out, this is the expected behaviour: `tui` assumes the render area is clean on the first draw. I don't know if it is possible for `tui` to query the current state of the terminal when it takes over. Even if it is the case this is a different feature request :). However, I understand how this can be confusing so I've mentioned this in the documentation of `Clear` in the meantime.
