### ISSUE TITLE
Styling gauge label with foreground / background color has no effect

### ISSUE THREAD

**Issue by ecklf** [fdehau/tui-rs#480]
## Description
Passing a styled span won't style fg/bg for the gauge label.

## To Reproduce
```rs
let gauge = Gauge::default()
    .gauge_style(Style::default().fg(Color::White))
    .percent(80)
    .label(Span::styled(
        "Progress is 80",
        Style::default()
            .fg(Color::Red)
            .add_modifier(Modifier::BOLD | Modifier::ITALIC),
    ))
    .block(
        Block::default()
            .borders(Borders::ALL)
            .border_type(BorderType::Plain)
            .title("Progress"),
    );
```

## Expected behavior
For the above example, I would expect the label to be red, bold, and italic at all times. However only bold and italic get applied.

## Screenshots
My output for reproduction example:
![image](https://user-images.githubusercontent.com/8146736/118024292-d19da780-b35e-11eb-85ce-0a682066892b.png)

## Environment
- OS: macOS
- Terminal Emulator: iTerm2
- Font: JetBrainsMono (patched NerdFont)
- Crate version: version = "0.15.0", default-features = false, features = ["crossterm"]
- Backend: crossterm

**Comment by fdehau** [comment]
Hey 👋, thanks for the bug report. This should be fixed by https://github.com/fdehau/tui-rs/pull/494/commits/6af37dbeca38093b8cbdf86d97184058a30cbad9. Feel free to reopen if that's not the case 😃
