### ISSUE TITLE
Getting Cursor Position in Wrapped Text

### ISSUE THREAD

**Issue by thorlucas** [fdehau/tui-rs#482]
## Problem
I'd like to get the cursor position in a paragraph widget with wrapping enabled. This is non trivial to calculate without basically rewriting the wrapping code. More generally, I'd like to be able to get information about the way Wrap has split up my text, so that I can move the cursor throughout the text.

## Solution
Add some function to `Paragraph` that allows us to get row and column information.

**Comment by Niederb** [comment]
I'm also interested in this feature. Did you find some kind of workaround to get the position with wrapped text?

**Comment by TBS1996** [comment]
> I'm also interested in this feature. Did you find some kind of workaround to get the position with wrapped text?

I made a workaround, but its not that pretty. I made a vector containing the start of each column when it's wrapped, which I did by starting from beginning position, iterating over the text and counting the amount of whitespace or non-whitespace in a row, when I hit the length of the consecutive whitespace I subtract that from where the next line would start, as that's the amount the text has ben wrapped

**Comment by AlvaroParker** [comment]
Another workaround is to append the block or line cursor character (█ or ︳) to the end of your string and pop it and push it again every time you add a new char. Is dum but it works.
