### ISSUE TITLE
Key::Char('q') seems to be kinda hardwired to "close app".

### ISSUE THREAD

**Issue by salkin-mada** [fdehau/tui-rs#491]
## Description
The key `q` is often used to either `break;` or do a ` self.should_quit = true;` Which is nice. Makes sense.
But when **not** using it: a `q` key press freezes the app.

## To Reproduce
Using the `termion_demo`.  Minimum code change and example.
1. in `demo/app.rs` change `pub fn` starting on line `#202` to:
```rust
    pub fn on_key(&mut self, c: char) {
        match c {
            // 'q' => {
            //     self.should_quit = true;
            // }
            't' => {
                self.show_chart = !self.show_chart;
            }
            _ => {}
        }
    }
```
2. `cargo run --example termion_demo`
3. Move around with arrow keys
4. Press key **q**
5. Try to move around with arrow keys again  _**(nothing happens, the cli app is frozen)**_

## Expected behavior
Nothing besides that the app should keep doings its thing.

## Environment
- OS: Linux
- Terminal Emulator: alacritty
- Crate version: 0.15
- Backend: termion

**Comment by fdehau** [comment]
Hey 👋, thanks for the report. This is happening because the thread spawned by the `Events` handler is also aware of the exit key and stop listening for input once it has been pressed. So the exit key had to be configured in two places to work properly. However, this is unnecessary as explained in #493. This change will make the app behaves as you expected.

**Comment by salkin-mada** [comment]
very nice. thanks for a fantastic crate @fdehau

**Comment by salkin-mada** [comment]
I now looked at the Events handler -> Config default. And it all makes sense. Thanks for elaborating on this.  I did not notice the key declaration in the utils. And instead of just using `skim` with a `rg -S -n` cmd on the examples folder i got confused and posted this issue. hehe.
If there should be a default exit key expectancy i would vote for <`C-c`>
