### ISSUE TITLE
manipulating ListState/TableState offset

### ISSUE THREAD

**Issue by wookietreiber** [fdehau/tui-rs#495]
## Problem

The `offset` of `ListState` and `TableState` can neither be accessed nor manipulated. 

## Solution

Add publicly visible `fn offset` and `fn offset_mut` to both `ListState` and `TableState`. 

## Alternatives

None.

## Additional context

Offset manipulation is needed to implement controls to center the view around the currently selected list item or row, e.g. like Emacs' `recenter-top-bottom` via `C-l` shortcut.

**Comment by Ranguna** [comment]
+1 for this, I'm looking for a way to get the offset value as well, so I can properly place a cursor on the active selection, which is not always obvious due to scrolling.

**Comment by bugnano** [comment]
This is a super useful feature to have, and it has already been attempted with PR #408 which is unmerged since 2020.
