### ISSUE TITLE
Unable to reproduce examples as standalone projects

### ISSUE THREAD

**Issue by LV-6502** [fdehau/tui-rs#500]
## Description

Sincere apologies in advance as this is most likely a user error (I'm new to the language)
I have attempted to compile the 'tabs.rs' file from inside the 'examples' folder as a standalone project to tinker with. 

Unfortunately I keep getting:
```
error[E0432]: unresolved import `util::event`
 --> src/tabs.rs:4:11
  |
4 | use util::event::{Event, Events};
  |           ^^^^^ could not find `event` in `util`
```

To try and fix this I added the following into the cargo.toml (see below for complete write up):
```
util = { path = "/home/xx/Desktop/RustTermUI/src/util"}
demo = { path = "/home/xx/Desktop/RustTermUI/src/demo"}
```
However this results in a
```
Caused by:
  failed to load source for dependency `demo`

Caused by:
  Unable to update /home/xx/Desktop/RustTermUI/src/demo

Caused by:
  failed to read `/home/xx/Desktop/RustTermUI/src/demo/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

## To Reproduce

**My directory structure is as follows:**
```
src
    |__demo
    |      |__app.rs
    |      |__mod.rs
    |      |__ui.rs
    |
    |__util
    |      |__event.rs
    |      |__mod.rs
    |
    |__tabs.rs
```

**The following entries have been added into Cargo.toml:**
```
[package]
name = "RustTermUI"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
rand = { version = "0.7.3", default-features = false, features = ["std"] }
tui = { version = "0.15", default-features = false, features = ['termion','serde'] }
thiserror = "1.0"
argh = "0.1"
util = { path = "/home/xx/Desktop/RustTermUI/src/util"}
demo = { path = "/home/xx/Desktop/RustTermUI/src/demo"}


[[bin]]
name = "tabs"
path = "src/tabs.rs"
```

**The code that calls the module:**
```
#[allow(dead_code)]
mod util;

use crate::util::{
    event::{Event, Events},
    TabsState,
};
```

## Environment

- OS: Ubuntu 20.04.2 LTS
- Terminal Emulator: System Terminal
- Font:
- Crate version:
- Backend: Termion

**Comment by chromafunk** [comment]
same problem here, including tui-rs as dependency of another project ... ideally you would be able to cleanly add an example out of the box. I'm also new to Rust so I will be following this thread. Thanks for posting.

**Comment by chromafunk** [comment]
What's happening here is that I create "util" directory in src, then : 

```
mod util;

use crate::util::event::{Event, Events};
```

The module is successfully detected, but the second line where we want to use util::event, the compiler complains it can't find /util/event.rs even though it is there ...

**Comment by chromafunk** [comment]
quick and dirty solution : just add the events code to the top of the demo file and do minimal refactor to clear duped includes :)

**Comment by LV-6502** [comment]
> 
> 
> quick and dirty solution : just add the events code to the top of the demo file and do minimal refactor to clear duped includes :)

Interesting... Do you mind sharing which version of Rust/Cargo you're on? Genuinely curious whether this is a user error (poor project config) or an actual issue with the compiler.

Appreciate the quick fix!

**Comment by chromafunk** [comment]
`rustc 1.53.0 (53cb7b09b 2021-06-17)`

```
[package]
name = "signal-visuals"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.9"
serde_json = "1.0.59"
serde = "1.0"
serde_derive = "1.0"
tui = "0.15"
termion = "1.5"
rand = "0.8.4"
```
I just created the project the way is suggested in the Rust documentation. I also get a directory not found error in cargo when I try to add a local dependency the way you did in your report ... still looking in to how to include external crates successfully here

**Comment by AndrewFeeney** [comment]
I found I had to delete `#[cfg(feature = "termion")]` (line 1 of `src/util/mod.rs`)  https://github.com/fdehau/tui-rs/blob/fbd834469fd99c7408a20ed09c5e205fe994c678/examples/util/mod.rs#L8 and was able to compile after that.

**Comment by LV-6502** [comment]
@AndrewFeeney Ideally though, should we be creating/configuring the CFG? If yes, do you know how?

Thanks for sharing the root cause!
