### ISSUE TITLE
Regression: styled gauge label color not inverted when overtaken by progress bar foreground

### ISSUE THREAD

**Issue by sputnick1124** [fdehau/tui-rs#538]
## Description

There seems to be a regression in the rendering of gauge labels between v0.14.0 and v0.16.0. Specifically in https://github.com/fdehau/tui-rs/commit/38dcddb12664f8939c90fe8b652037027ad848d8 is where the issue was introduced. In the previous version, one could apply a color style to a gauge label and the color would be properly inverted when overtaken by the progress bar foreground color. Since the above commit, this no longer happens; rather, the label color remains the same throughout, meaning it is obscured by the progress bar if the label foreground and gauge foreground are the same color.

## To Reproduce

This snippet was adapted from the gauge example:
```rust
    loop {
        terminal.draw(|f| {
            let chunks = Layout::default()
                .direction(Direction::Vertical)
                .margin(2)
                .constraints(
                    [
                        Constraint::Percentage(25),
                    ]
                    .as_ref(),
                )
                .split(f.size());

            let label = Span::styled(
                format!("{}%", app.progress),
                Style::default()
                    .fg(Color::Yellow)
                    .add_modifier(Modifier::ITALIC | Modifier::BOLD),
            );
            let gauge = Gauge::default()
                .block(Block::default().title("Gauge").borders(Borders::ALL))
                .gauge_style(Style::default().fg(Color::Yellow).bg(Color::Red))
                .label(label)
                .percent(app.progress)
                .use_unicode(true);
            f.render_widget(gauge, chunks[0]);
        })?;

        match events.next()? {
            Event::Input(input) => {
                if input == Key::Char('q') {
                    break;
                }
            }
            Event::Tick => {
                app.update();
            }
        }
    }
```

When this is compiled with the current HEAD, it produces the following gauge:
![v0 16 0](https://user-images.githubusercontent.com/8843309/135951391-e3377184-a159-4581-bbf5-a7bc4f14b38f.gif)

## Expected behavior

In previous versions, this same code produces the following gauge render (to be more precise, one can take the current master and do simply `git checkout v0.14.0 -- src/widgets/gauge.rs` and get this proper render):
![v0 14 0](https://user-images.githubusercontent.com/8843309/135951636-a3e4ab9d-6774-46ce-aae7-dad8a40f0831.gif)

## Environment
- OS: Linux / Ubuntu 18.04
- Terminal Emulator: alacritty
- Font: Cascadia Code
- Crate version: 0.16.0
- Backend: termion

## Additional context

I think this is likely just a matter of order of operations, but I don't have enough background in the gory details of terminal coloring to be sure about that.

**Comment by fdehau** [comment]
Hey 👋 . This is not a regression. If you look at the [original issue](https://github.com/fdehau/tui-rs/issues/480) that motivated this change, the label colors were never taken into account previously.

The style hierarchy in the gauge widget is: `label style > gauge style > block style`

Therefore if you create your label with:
```rust
 let label = Span::styled(
                format!("{}%", app.progress),
                Style::default()
                    .fg(Color::Yellow)
                    .add_modifier(Modifier::ITALIC | Modifier::BOLD),
            );
```
The gauge will make sure the label is always `Color::Yellow`. If you want to return to the automatic inversion of colors, don't set a foreground color on your label:
```diff
 let label = Span::styled(
                format!("{}%", app.progress),
-               Style::default()
-                  .fg(Color::Yellow)
-                  .add_modifier(Modifier::ITALIC | Modifier::BOLD),
+               Style::default().add_modifier(Modifier::ITALIC | Modifier::BOLD),
            );
```
