### ISSUE TITLE
Non-static str "problem"

### ISSUE THREAD

**Issue by nothingButSyntaxError** [fdehau/tui-rs#545]
## To Reproduce
 file-manager/src/lib.rs:52:30
   |
37 |             .paint(|ctx| {
   |                    ----- value captured here
...
52 |                 for path in &vector {
   |                              ^^^^^^ borrowed value does not live long enough
53 |                     ctx.print(-65.0, _y, &path, Color::Blue);
   |                     ---------------------------------------- argument requires that `vector` is borrowed for `'static`
...
59 |     })?;
   |     - `vector` dropped here while still borrowed```
-->

## Environment

Hope you fix this problem asap. Thank you. Feel free to tell me if this is a me problem or a problem with my code because as I said I am pretty new to this crate. Thank you again.

**Comment by wcampbell0x2a** [comment]
This doesn't have a full example, so I don't know what type `path` is, but I'm assuming a str related type.

See https://github.com/fdehau/tui-rs/issues/529 for a fix that exists on master.

**Comment by fdehau** [comment]
As @wcampbell0x2a mentions the next release will contain [a fix] (https://github.com/fdehau/tui-rs/pull/543) for `Context::print`. You'll be able to use owned strings and thus avoid this lifetime issue.
