### ISSUE TITLE
Migrating to Rust 2021 edition

### ISSUE THREAD

**Issue by orhun** [fdehau/tui-rs#556]
## Problem
2021 edition is now available in Rust stable `1.56+`. `tui-rs` uses 2018 edition. What's your thoughts on migrating to 2021? I would like to provide a PR.

## Solution

`cargo fix --edition`

## Alternatives
None

## Additional context
- https://doc.rust-lang.org/edition-guide/rust-2021/index.html

**Comment by fdehau** [comment]
Hey :wave: , if I'm not mistaken this implies that the minimum required rust version becomes `1.56+`. I usually like to wait a few months before pushing this requirement to crate users. I'm slowly making progress on a next release so depending on the cutoff date, we might include these changes.

Was this motivated by a change in the 2021 edition that might heavily benefit `tui` ?

**Comment by orhun** [comment]
> Hey wave , if I'm not mistaken this implies that the minimum required rust version becomes `1.56+`. I usually like to wait a few months before pushing this requirement to crate users. I'm slowly making progress on a next release so depending on the cutoff date, we might include these changes.

Sounds good 👍🏼 

> Was this motivated by a change in the 2021 edition that might heavily benefit `tui` ?

Not "heavily", but it surely brings some benefits and refactoring opportunities to the codebase.

I'm closing this issue for now, until the upcoming releases. Feel free to reopen when this is relevant / you want any help on migration :bear:
