### ISSUE TITLE
Add new backend (`zui`)

### ISSUE THREAD

**Issue by dumrich** [fdehau/tui-rs#557]
## Problem
I've created a new terminal backend called zui, and I'd like to try and add all the widgets that tui-rs provides to it.
https://git.dumrich.com/zui/about/

## Solution
As I am the author of this crate and have been using tui-rs for a while, I think that with some time I would be able to do this.

## Additional context
Some benefits to using `zui` is that it produces very small binaries and that it has a nice interface without directly writing much.

**Comment by fdehau** [comment]
I'm a bit reluctant to add another backend in the main crate right now. But you can easily add support for your project by implementing the [`Backend`](https://docs.rs/tui/0.16.0/tui/backend/trait.Backend.html) trait — which is unfortunately not well documented right now 😬 .
