### ISSUE TITLE
Extend 'App using TUI' list

### ISSUE THREAD

**Issue by Hyde46** [fdehau/tui-rs#559]
## Problem
Are there any specific prerequisits to get featured on the [App using TUI](https://github.com/fdehau/tui-rs#apps-using-tui) section of the README.md?
I've been working for a while on a CLI tool, [hoard ](https://github.com/Hyde46/hoard) with `tui-rs` as its core UI/UX library, and i've been having a blast with it! Without `tui-rs` I definitely could not have reached the current state it's in

**Comment by fdehau** [comment]
Hi! There aren't any prerequisites to be included in this list at the moment. I'm always happy to discover how people are using the crate. It is also a good way to show people what can be done with `tui` when they are evaluating it.

Feel free to send a PR to add your project to the list.
