### ISSUE TITLE
Updating the state of ListView contents

### ISSUE THREAD

**Issue by jackpeters667** [fdehau/tui-rs#565]
## Description
Hi there, not sure if this is a bug or maybe i'm missing something. But I have an input field and a listview. I want to filter the listview contents with the text in the input field. From my current setup, I have a `struct` that holds the list items and when I filter the contents of that list, I assign the results to another variable that I then set to be the items to use in the list view. The UI isn't refreshing with my new filtered content though. Is there something I should perhaps add?

## To Reproduce
```rust
struct App<'a> {
    name_filter: String,
    name_state: ListState,
    names: Vec<ListItem<'a>>,
    names_searched: Vec<ListItem<'a>>,
}
```
Provided that the `Listview` items are set like this:
```rust
        app.names_searched = app.names.clone();
        let items = List::new(&*app.names_searched)
            .block(Block::default().borders(Borders::ALL).title("Names"))
            .highlight_style(
                Style::default()
                    .add_modifier(Modifier::REVERSED)
                    .patch(Style::default().add_modifier(Modifier::BOLD))
                    .patch(Style::default().fg(Color::White)),
            );
```
Updating the `names_searched` list by a search:
```rust
// text entered on input box 
                            let filtered: Vec<_> = names
                                .iter()
                                .filter(|x| {
                                    x.name
                                        .to_ascii_lowercase()
                                        .contains(&app.name_filter.to_ascii_lowercase())
                                })
                                .collect();
                            app.names_searched = filtered
                                .iter()
                                .map(|i| {
                                    let lines = vec![Spans::from(i.name.to_string())];
                                    ListItem::new(lines).style(Style::default())
                                })
                                .collect();

```
If I set my ListView items based off the `names_searched` variable, am I able to update contents of the listview **just** by changing `names_searched`? If not, what else should I do?

**Comment by fdehau** [comment]
Hey 👋, I'm missing a bit of context to be able to find the root cause of your issue. Could you provide a minimum reproducible example ?

In `tui`, UI components are not stored, you build them dynamically as needed when you describe your user interface. Therefore, unless you really need to store `names_searched`, I would advise you to derive it from `names` — which should probably be a `Vec<String>` — and `names_filter` when you build your UI.

See the `filter` example on [this branch](https://github.com/fdehau/tui-rs/tree/filter-example) (`cargo run --release --example filter`).

**Comment by jackpeters667** [comment]
Thank you for the heads up on the `names_searched`. I had a feeling I was doing something wrong. 
Huge thanks for taking the time to write up an example for me. I just ran it and it works like a charm. Let me try to wrap my head around how you went about. Thanks for your awesome work. Closing this since it's not a bug but my implementation :smiley:
