### ISSUE TITLE
Termion is built even when having enabled only the crossterm feature

### ISSUE THREAD

**Issue by andreafioraldi** [fdehau/tui-rs#581]
Hi,
I'm using tui for a cross platform UI, and so I'm using crossterm as backend to have it working on windows.
My problem is that cargo is building termion even if I specify crossterm as the only feature for the crate and so the build breaks on windows.

You can reproduce simply creating a crate with these dependencies:

```
[dependencies]
tui = { version = "0.16", features = ["crossterm"] }
crossterm = { version = "0.20" }
rand = "0.8.4"
```

Then, with cargo build, you will have (on linux):

```
   Compiling libc v0.2.112
   Compiling cfg-if v1.0.0
   Compiling log v0.4.14
   Compiling signal-hook v0.3.13
   Compiling parking_lot_core v0.8.5
   Compiling smallvec v1.8.0
   Compiling scopeguard v1.1.0
   Compiling ppv-lite86 v0.2.16
   Compiling numtoa v0.1.0
   Compiling bitflags v1.3.2
   Compiling cassowary v0.3.0
   Compiling unicode-width v0.1.9
   Compiling unicode-segmentation v1.8.0
   Compiling instant v0.1.12
   Compiling lock_api v0.4.5
   Compiling signal-hook-registry v1.4.0
   Compiling getrandom v0.2.4
   Compiling mio v0.7.14
   Compiling termion v1.5.6
   Compiling rand_core v0.6.3
   Compiling parking_lot v0.11.2
   Compiling rand_chacha v0.3.1
   Compiling signal-hook-mio v0.2.1
   Compiling crossterm v0.20.0
   Compiling rand v0.8.4
   Compiling tui v0.16.0
   Compiling uitest v0.1.0 (/home/andrea/Desktop/uitest)
```

`   Compiling termion v1.5.6` :(

**Comment by andreafioraldi** [comment]
The issue seems fixed in git master, I'm using the version on crates, please update it ty

**Comment by fdehau** [comment]
This is not a bug :). The last version published use `termion` as a default feature. As [described in the doc](https://docs.rs/tui/0.16.0/tui/#adding-tui-as-a-dependency), you should disabled the default features when you want to use crossterm:
```
tui = { version = "0.16", default-features = false, features = ['crossterm'] }
                          ^^^^^^^^^^^^^^^^^^^^^^^^
```
