### ISSUE TITLE
Can you add borders between Columns / Rows and around Headers on a table?

### ISSUE THREAD

**Issue by matthewmturner** [fdehau/tui-rs#599]
## Problem

I would like to add more formatting to a table - such as borders around columns and header so that it is easier to read.  Is this possible? From what i see thats only possible in a `Block`.

**Comment by Y-jiji** [comment]
I made this work-around with manually computed rectangle locations. 
![image](https://github.com/fdehau/tui-rs/assets/71013200/9de75842-2bb5-46a2-af6f-6e861250d0bd)

**Comment by Y-jiji** [comment]
I hope it helpful when this requested enhancement is not yet available.
