### ISSUE TITLE
Widget: TreeView

### ISSUE THREAD

**Issue by nifker** [fdehau/tui-rs#60]
Im very interested to see a TreeView as another widget. Is it planned or in consideration?

**Comment by fdehau** [comment]
I don't have a plan for new widgets at the moment. Although I would consider adding new ones if they are particularly requested.

I'm uncertain about what a TreeView would look like. Would you mind sharing what you had in mind and why it would be a nice addition to this crate ?

**Comment by nifker** [comment]
Using these https://en.wikipedia.org/wiki/Box-drawing_character
It could look like:
Layer1
├Layer1_1
│└Element1_1-1
├Element1-1
└Element1-2
Layer2
├Element2-1
└Element2-2

And if you are not interested in adding one currently - what about issue https://github.com/fdehau/tui-rs/issues/62, but I think this is more a problem, especially when writing texts in TUI https://github.com/fdehau/tui-rs/issues/63

**Comment by alok** [comment]
I'd love this widget, since one app I use is just a todo list that manipulates a bunch of subtrees.

**Comment by extrawurst** [comment]
Just as an FYI for people coming across this, a lack of a generic widget for this does not keep anyone from rolling their own - here is my example of a tree view which is rendered using the `SelectableList`:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/776816/80570658-7d49b300-89fb-11ea-8632-9a38ee05dcd8.png">

**Comment by joshka** [comment]
There is also https://github.com/EdJoPaTo/tui-rs-tree-widget which will be merged into ratatui sometime soon.

- [x] Has related ratatui issue / PR:
  - https://github.com/tui-rs-revival/ratatui/pull/157
  - https://github.com/tui-rs-revival/ratatui/issues/116
