### ISSUE TITLE
Can tui-rs use sixel / kitty graphics protocol / arbitrary escape sequences in cells?

### ISSUE THREAD

**Issue by lf94** [fdehau/tui-rs#604]
Please see https://gist.github.com/lf94/d3819115b7c97ddebc9867e5b06116a5 for what I'm trying to achieve this week.

I want to use tui-rs for layout, but I need to be able to also render images in some places.

I have looked into using `notcurses` but it is largely not rust-ready. There is a low-level binding but it is very, very terrible to use as a developer. The high level wrapper is not ready or looks to have stalled.

From what I understand, tui-rs is capable of interacting at a lower level when needed. With this assumption, I can probably use it in combination with a sixel package?

Thank you!

**Comment by lf94** [comment]
https://docs.rs/tui/latest/tui/buffer/struct.Cell.html I think could make this work, the only "blocker" is getting tui-rs to fire the correct escape sequence to get the terminal into "sixel mode": `ESC+Pp1;p2;p3;q` (Source: Wikipedia)

**Comment by lf94** [comment]
https://docs.rs/tui/latest/tui/backend/struct.CrosstermBackend.html using `write` could allow for the escape sequence to be entered?

**Comment by lf94** [comment]
```rs
    term.draw(|f| {});
    term.backend_mut().write(&[0x1B,0x50,0x71])?;
    term.backend_mut().write(
     b"#0;2;0;0;0#1;2;100;100;0#2;2;0;100;0#1~~@@vv@@~~@@~~$#2??}}GG}}??}}??-#1!14@"
    )?;
    term.backend_mut().write(&[0x1B,0x5C])?;
```
Unfortunately doesn't seem to output anything.

**Comment by lf94** [comment]
After some playing I think tui-rs could easily use either sixel or kitty graphics protocol if it exposes the backend's `write` and `flush` methods. What do you think?

**Comment by lf94** [comment]
https://docs.rs/tui/latest/src/tui/terminal.rs.html#63 making this public would allow this to work.

**Comment by lf94** [comment]
This is my latest attempt, hoping that `Cell` can just hold onto the escaped sequence:

```rs
struct Thing {}

impl Widget for Thing {
    fn render(self, area: Rect, buf: &mut Buffer) {
      if area.area() == 0 {
          return;
      }
      let cell = buf.get_mut(area.x, area.y);
      cell.set_symbol("\x1B_Gf=100;t=f;/home/lee/Pictures/1646177580.png\x1B\\");
    }
}


fn main() -> Result<(), io::Error> {
    enable_raw_mode()?;
    let mut stdout = io::stdout();
    execute!(stdout, EnterAlternateScreen, EnableMouseCapture)?;

    let backend = CrosstermBackend::new(stdout);
    let mut term = Terminal::new(backend)?;

    term.draw(|f| {
      let size = f.size();

      let block = Block::default()
          .title("Block")
          .borders(Borders::ALL);
      f.render_widget(block, size);

      let thing = Thing {};
      f.render_widget(thing, size);

    })?;

    thread::sleep(Duration::from_millis(5000));

    disable_raw_mode()?;
    execute!(term.backend_mut(), LeaveAlternateScreen, DisableMouseCapture)?;
    term.show_cursor()?;

    Ok(())
}
```

**Comment by lf94** [comment]
Haha! It works!!

![1647733650](https://user-images.githubusercontent.com/547923/159142173-d4984247-54d9-41ac-948e-a03d487c2c3d.png)

All right, onto phase 2 of my master plan! This issue can now be closed now.

**Comment by plasticalligator** [comment]
guys if we keep it up maybe some day we'll be able to get rust on par with megazeux.
