### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by nifker** [fdehau/tui-rs#61]
How about Scrollbars for Tables and similiar widgets or a related solution?

**Comment by nifker** [comment]
Currently closed as not required

**Comment by fdehau** [comment]
First of all what usage do you see for scroll-bars ? As an intensive user of terminal applications, I've never found myself in a position where scroll-bars would be helpful. I usually expect to have that kind of behavior accessible through key bindings or using the scroll wheel. Moreover, it might be a bit tricky to get input from the user (at least given the current design of the crate). So, I'm currently only seeing them as a way to provide some feedback to user.

However, there is definitively a need to improve the navigation inside lists, tables, etc...

**Comment by nifker** [comment]
it was thought for proving feedback where you are in the list/table.

**Comment by fdehau** [comment]
Ok =) So I will keep this open to remind me to consider those when I'm revisiting the navigation inside lists and tables.

**Comment by joshka** [comment]
- [x] There is a related issue discussing this in depth over in ratatui:
 - https://github.com/tui-rs-revival/ratatui/issues/174
