### ISSUE TITLE
Make cursor not flash (option)

### ISSUE THREAD

**Issue by peepopoggers** [fdehau/tui-rs#613]
## Problem

I am frustrated when my cursor flashes. I rage.

## Solution

Add option to make cursor not flash

## Alternatives

I can keep raging.

**Comment by fdehau** [comment]
👋 Closing because this is not a proper nor a nice way to file an issue or ask for help. Please look at the issue template for bug reports next time.

**Comment by peepopoggers** [comment]
oh sorry :) by the way, I think it is terminal dependant, when using alacritty it does not flash.

**Comment by peepopoggers** [comment]
It can apparently be disabled in crossterm by placing `DisableBlinking` in `execute!(...)` macro.
