### ISSUE TITLE
Word wrapping for list elements

### ISSUE THREAD

**Issue by peepo5** [fdehau/tui-rs#616]
## Problem

I have an app where I emulate a terminal, and I provide output to the user. It has been going ok so far, but an issue is that text too long for the screen does not wrap round. I looked at the wrap method, but it only looks like it is for paragraph elements, not list/list item elements.

## Solution

A method for list elements for word wrapping.

## Alternatives

If such a feature exists in this crate somehow, then I would like to know how to use it.

**Comment by invokermain** [comment]
Also been struggling to figure this out, can wrap things manually but it is very unreliable. Obviously being able to use Paragraph's wrapping logic would be great.

**Comment by peepopoggers** [comment]
Yeah, you could keep a vector of tuples containing (String, u16) or something similar. Then you could use the width of the list element to calculate where to split the string. Then the first part could be added to the vector like ("Hello...", 0), and it could loop so the second one is checked again for its length, and it could be added like ("blah", 1), with 1 explaining that it is the first wrap for the original element. This could be done on every render, and it would be a good idea not to run unless a specific amount of ms has passed to make sure to not use that many resources.

Another way (referenced in another issue) is wrapping words without cutting them, by splitting by space to see if it is less than the width of the list element.

Both options are valid, but I think there should be an in-built functionality like this.

**Comment by peepopoggers** [comment]
For my message above, just as a note for anyone that wants to do this, you could keep the list as a `Vec<String>` or similar, and then you could transform it into `Vec<(String, u16)>` before you draw the list element, by doing the instructions I said above. This would make inserting text easier, as wrapping is done automatically.

**Comment by peepopoggers** [comment]
This library may be helpful too -> https://github.com/mgeisler/textwrap
