### ISSUE TITLE
Lock terminal scrolling

### ISSUE THREAD

**Issue by nifker** [fdehau/tui-rs#62]
Is there a function which prevents one from scrolling outside the application? As it is still possible to use the terminal scrollbar to scroll up.
Or is this rather a question for the termion issues?

**Comment by fdehau** [comment]
Are you encountering the same issue as #8 or is it a different behavior ? Using the `MouseBackend` from the `termion` backend should capture mouse events and thus remove the ability to scroll.

**Comment by nifker** [comment]
@fdehau its still possible - not with the scroll wheel but using the terminals own scrollbar - nano doesnt have this behavious Ill be looking that ones source code, maybe Ill be able to find something.

**Comment by fdehau** [comment]
Then I think, you may need to use the `AlternateScreenBackend`. From my understanding, it disable the scroll back buffer and restore it when the application exits.

**Comment by nifker** [comment]
@fdehau Yes that works :D
