### ISSUE TITLE
Allow control on the offset of TableState

### ISSUE THREAD

**Issue by MrCasCode** [fdehau/tui-rs#626]
## Problem
When using a Table widget to view millions of entries the performance is largely impacted (which is normal, since its working with 5GB of data). 

In these scenarios is interesting to have a Lazy building state which fetches new items to work with only a small subset of data. 

The problem appears when changing the items the table represents as a rolling window. 
· Scrolling down fetches next N elements and removes previous N elements to have a constant size
· Scrolling up fetches previous N elements and removes next N elements to have a constant size

Since I'm modifying the internal items represented I need to reselect the appropriate index but this is not a smooth transition for the user because I can't control the TableState offset and the selected item jumps to the bottom after the changes.

In order for this to be smooth for the user I need access to the offset to set it to the correct position when scrolling up so that the reload is unnoticeable. 

## Solution
A) Make the TableState offset member public:
````rust
pub struct TableState {
    pub offset: usize,
    selected: Option<usize>,
}
````
B) Add a public setter:
````rust
pub struct TableState {
    offset: usize,
    selected: Option<usize>,
}

impl TableState {
    pub fn offset(&mut self, offset: usize) -> Option<usize> {
        self.offset = offset
    }
}
````
## Alternatives
· Change the Table implementation so that the State template type is a trait that can be implemented. By doing so one could create it's own implementation of TableState, which makes sense since we are already working with this object to manage the object state.

· If the proposal is not accepted, one could copy the entire code of the Table widget to make few changes. But this is very undesirable.

· The other workaround is to use unsafe to set the state of TableState when needed, but this is ugly
```rust 
unsafe {
     self.state = std::mem::transmute::<(usize, Option<usize>), TableState>((offset, Some(index)))
}
```

**Comment by Ternvein** [comment]
To address this problem, I'd rather added an interface allowing to pass a callback to `Table` (and probably `List` as well), which should be called when widget is about to render row `X`, passing `X` as an argument to the callback. This will allow to optimize huge tables and lists drastically on the user side.
Something like that:
```rust
table.data_callback(|idx| Row::new(data[idx]));
```
