### ISSUE TITLE
Avoid string allocation on Cell

### ISSUE THREAD

**Issue by kvark** [fdehau/tui-rs#627]
## Problem
I admit tui-rs isn't supposed to be extra fast. Yet. `Cell::symbol` is a fully formed heap-allocated `String`, which seems like a big waste?

## Solution
Could it just be a `char`?

## Alternatives
If it has to be a string , then it could be `&'a str` at least. The user could create a single string and make the cells see sub-slices of it.

## Additional context
Related to #535

**Comment by rhysd** [comment]
I created a PR which would fix this issue. Since one cell contains one Unicode grapheme cluster, `char` is not available. Instead I used [`smol_str`](https://github.com/rust-analyzer/smol_str) crate which is maintained by rust-analyzer team.
