### ISSUE TITLE
Unable to generate widths dynamically

### ISSUE THREAD

**Issue by hommeabeil** [fdehau/tui-rs#629]
## Problem

This is more of a question. I am wondering why the `widths` field in the `Table` struct is a reference ? This force me to either create the constraint statically at compile time or to define them in an upper lifetime scope. Simply said, I can't create a Table in a fonction if I compute the constraint dynamically. Maybe I am not using the `widths`correctly ?

I am really new to this lib, so any comments are welcome. Thanks

**Comment by enricozb** [comment]
I'm having the same issue. I've written a my own `Table` that dynamically assigns column lengths based on the data, but I'm having a hard time specifically around passing around a dynamically generated `&[Constraint]`. A rough example of what I tried to do looks like this:

```
struct MyTable {
  title: Option<String>,
  data: ...,
}

impl MyTable {
  pub fn widget(&self) -> tui::widgets::Table {
    let constraints = ...;

    tui::widgets::Table::new(...).widths(&constraints)
  }
}
```

**Comment by enricozb** [comment]
I ended up solving this by having my struct implement `Widget` and `StatefulWidget`. Ownership of the constraints doesn't matter as much because rendering destroys the table. Maybe this will help you @hommeabeil

**Comment by hommeabeil** [comment]
I will looks into it thanks.

**Comment by sinKettu** [comment]
Hello! Faced with the same issue. I need to calculate table's widths for changing width of a terminal. I Did not understand advice about `StatefulWidget`. Can somebody help please?

**Comment by enricozb** [comment]
Here's a simplified version of what I did. I have a custom `MyTable` structure:
```
pub struct MyTable {...}
```
with all of the data required to compute the table widths. Then you can implement `Widget` for your table:
```
impl<'a> Widget for Table<'a> {
  fn render(self, area: Rect, buf: &mut Buffer) {
    let constraints = self.constraints();

    Widget::render(self.widget(&constraints), area, buf);
  }
}
```

I had to make a `MyTable::constraints` function that would return the computed constraints as a `Vec<Constraint>`, and then `MyTable::widget` takes in the constraints and returns a `tui::widgets::Table` that can be rendered.

If you implement the `Widget` trait for your table then you can render it like this
```
frame.render_widget(MyTable::new(...), table_rect);
```

Hopefully this helps!
