### ISSUE TITLE
Better scroll view

### ISSUE THREAD

**Issue by xixixao** [fdehau/tui-rs#694]
Currently Paragraph allows wrapping text and scrolling, but it has 2 major shortcomings:

1. There is no way to know how many wrapped lines there are. Hence it's not possible to implement "scroll_to_end" and similar functionality
2. Wrapping is done at render time. If the original Text is very large this can be very expensive - and uncessarily so.

I do have an implementation of a scrollview as a `StatefulWidget` that solves these problems, which I copied to: https://gist.github.com/xixixao/c2e9cdfac47753b823b34b9e29cc3d26

I'd be happy if some version of this made it back to the library.

**Comment by mindoodoo** [comment]
Hey, we're working on a fork over [here](https://github.com/tui-rs-revival/tui-rs-revival), if you have the time, please open this issue over there / eventually open a PR implementing the relevant parts of your scrollview.

Keep me posted !
