### ISSUE TITLE
Using min and max constraints together results in inconsistent (random) layout.

### ISSUE THREAD

**Issue by max-ishere** [fdehau/tui-rs#703]
## To Reproduce
```rust
let chunks = Layout::default().constraints([
    Constraint::Max(terminal.size()?.height - 2), // 0
    Constraint::Length(1),                        // 1
    Constraint::Min(1),                           // 2
])
```
Sometimes makes `chuncks[0]` fill up the screen and the `chunks[2]` is just one line. Sometimes `chunks[0]` is just not there at all and there's a bunch of empty space on the bottom because 2 took up all the space.

## Expected behavior
The layout should come out the same way every time. Honestly it doesnt matter if its the way I want it to be or not it has to be the same every time I run it.

## Screenshots
```text
┌Tree vie┐┌List───────────────────┐
│        ││Item 1                 │
│        ││Item 2                 │
│        ││Item 3                 │
└────────┘└───────────────────────┘
Modeline
Logs
```
```text
Modeline
Logs





```

## Environment

- OS: Linux
- Terminal Emulator: Alacritty
- Font: Monospace
- Crate version: 0.19.0
- Backend: Crossterm

**Comment by mindoodoo** [comment]
Hey :wave: 

This crate isn't being worked on anymore, if you're interested, you can reopen your issue over on the [ratatui](https://github.com/tui-rs-revival/ratatui) repo. Ratatui is the new community maintained fork of this wonderful crate !
