### ISSUE TITLE
README should say that tui is unmantained and ratatui is the maintained fork

### ISSUE THREAD

**Issue by god-is-a-crab** [fdehau/tui-rs#709]
## Problem
I can't find anywhere in the README that says this project unmaintained. I think there should be a mention that ratatui is the maintained fork. Would it be a good idea to add this to the README?

**Comment by orhun** [comment]
This would be a reasonable thing to do. Also, we recently had a meeting (see the [notes](https://github.com/tui-rs-revival/ratatui/discussions/316)) and planning to transfer ownership (if possible).
