### ISSUE TITLE
Add Europe Map

### ISSUE THREAD

**Issue by kpcyrd** [fdehau/tui-rs#72]
The world map is really cool, any chance you could extend this so I can select Europe instead of the whole world? blessed-contrib currently has a USA map, but no map for Europe.

Thank you!

**Comment by fdehau** [comment]
You can already select the area drawn on the `Canvas` widget using `y_bounds` and `x_bounds`. For a small widget the current data for the map should have a good enough resolution. However, if you need more precise data, you might checkout the [website](http://www.gnuplotting.org/plotting-the-world-revisited) where I found the data in the first place. Files with the higher resolution would be too big to draw at each frame but a subset of it (in your case Europe) should be fine. Then it is a matter of passing this data to a `Canvas` widget using the `Points` shape.

Let me know if that's enough for your use case.
