### ISSUE TITLE
Feature request: Linechart

### ISSUE THREAD

**Issue by cjbassi** [fdehau/tui-rs#73]
I think it would be nice if we had an option for the chart widget to draw lines between each marker. I saw you were able to have a linechart in `examples/demo.rs` but only when feeding in continuous data. Maybe add an option to the chart widget or create a new linechart struct to enable drawing a line between consecutive points. I could probably hack a pr together but I wasn't sure what the best way to implement it would be.

**Comment by fdehau** [comment]
I would like to first make sure that I understand your proposition. Is it a matter of adding new points in between using the same marker or to use dot symbol for the points and braille symbols for the lines ? In the first case, it may be hard to achieve with the current version of the `Chart` widget (maybe a wrapping iterator over the data provided by the user). In the second case, a new widget is definitively a better idea.

**Comment by cjbassi** [comment]
I was thinking of the first option I think. Basically getting the functionality as seen in the gif in the readme without having to provide continuous data. So adding lines between markers using the same marker style.
