### ISSUE TITLE
Feature request: Dynamic dispatch chain

### ISSUE THREAD

**Issue by gin66** [fdehau/tui-rs#75]
from my point of view, the dynamic rendering is complemented well with a dynamically build dispatch chain. This approach I have used in tui-logger-widget and IMHO works quite well. Just I would prefer, that this is an integrated part in tui-rs instead of the widget.

Have you thought about using similar dynamically built dispatch chain ?

**Comment by fdehau** [comment]
First of all I'm not totally sure what you mean by a dynamic dispatch chain. A more detailed explanation might help this idea to be considered.

From a quick glance at your work on tui-logger I would understand that it is a matter of binding key input to state updates. But I'm also seeing that this is mixed inside the render function so I'm not sure of the capabilities of such feature.

Finally, the crate has never made any assumptions about how the input is handled or the state managed giving users the freedom to use the existing terminal libraries as they wish. I'm worried that choosing such an opinionated way of handling input (if I understood your point correctly) might introduce friction for users wanting to build things using an other way.

**Comment by gin66** [comment]
Thanks for answering and checking my code.

The dynamic dispatch allows for such a nested widget to react on the displayed content. On second thought, this too means, the widget is not stateless and needs a means to store this state, which does not fit well to the basic tui.rs concept. So I agree with you, that this may cause friction for users using tui.rs in another way.
