### ISSUE TITLE
Regarding cursor state when text input

### ISSUE THREAD

**Issue by Escapingbug** [fdehau/tui-rs#83]
AFAIK, currently there's no way to modify cursor state.. So if I want a text input, like a line editing, I'd like the user to see the cursor, so they know where they are editing. But I don't see anything like editing cursor position when editing. There are only "show" and "hide" cursor. So, how can this be achieved?

**Comment by fdehau** [comment]
This is actually something that you may be able to achieve by accessing the underlying `backend`. I've edited the `user_input` example to showcase that:  https://github.com/fdehau/tui-rs/commit/32947669d51e2e65499bdc054119db82c8189917.
