### ISSUE TITLE
Question: Best way to draw a Buffer directly?

### ISSUE THREAD

**Issue by jrmiller82** [fdehau/tui-rs#86]
I'm making a TUI game, and I'm having trouble figuring out the best way to place a single character into a `Rect`. I see the `Buffer` methods and doing it that low-level is just fine, the question is how do I then render the `Buffer`? Do I have to make a custom widget for that?

**Comment by fdehau** [comment]
Custom widget is effectively the best way to draw to a Buffer directly. The second argument of the `Widget::draw` method is the area where the widget is supposed to be drawn and thus the same area as the one given in `Widget::render`

**Comment by jrmiller82** [comment]
Thanks. I figured out what I wanted to do by using the Paragraph widget and making a Rect of width = 1 and height = 1. I still think it might be a good idea to add a widget called something like "RawBuffer" that lets you use the Buffer.FOO methods on it.
