### ISSUE TITLE
Improve scrolling behavior of selectable lists

### ISSUE THREAD

**Issue by dotdash** [fdehau/tui-rs#96]
The current scrolling behavior of selectable lists somewhat confusing. Currently, when you're at the bottom of the window and you select the previous entry, instead of just moving the selection up, the list scrolls up and the selected row is still at the bottom. I'd much rather have the list only scroll when I already hit the top or bottom of the currently visible rows.

Additionally, I'd love to have support for a scroll offset. That is, a set amount of rows that is kept above or below the selected row, i.e. the list starts scrolling X rows before you hit the top/bottom. One reason is that this allows you to see whether there are still more rows to come even without a scrollbar.

**Comment by fdehau** [comment]
The scrolling behavior of `List` has been updated in #210. It will be available in the `0.9`release.
