### ISSUE TITLE
Question/Feature Request: Why does `Text::raw` get rid of `\t` tabs?

### ISSUE THREAD

**Issue by jrmiller82** [fdehau/tui-rs#98]
I'm not getting the expected behavior of `Text::raw` used in a `widget::Paragraph`. It's not honoring `\t` in the text, however, it is honoring `\n`. Am I doing something wrong? Is there a reason this isn't working? 

```
let x = format!("No indent\n");
let y = format!("\tThis should indent.");
let text = Text [Text::raw(&x), Text::raw(&y)];
Paragraph::new(text.iter())...
```

I expect the second line to be indented by a tab, but it's flush left with the first line start.

**Comment by DarrienG** [comment]
This bug is also present with Text::styled.

**Comment by iximeow** [comment]
i'm not sure what a _fix_ looks like, but the cause looks like how `width` is used in [`set_stringn`](https://github.com/fdehau/tui-rs/blob/43e38ac483de53f542cccecdd82d36b7996342af/src/buffer.rs#L319): as far as `unicode-width` is concerned, control characters have [zero width](https://github.com/unicode-rs/unicode-width/blob/4940d3fe277a6de0ae640411d7d16ec1c76dbbc5/src/tables.rs#L43), so it looks like the `\t` is simply overwritten when printing the next character.

happened to run across this looking at a different bug, just wanted to add some notes here

**Comment by orhun** [comment]
You can try this for spacing: (at least for now)
```
let x = format!("\u{2800}   indent");
```
https://www.compart.com/en/unicode/U+2800

**Comment by ilyagr** [comment]
I'm confused by @orhun 's suggestion. What is the reason to use `\u{2800}` and 4 spaces as opposed to 5 spaces?

**Comment by orhun** [comment]
> I'm confused by @orhun 's suggestion. What is the reason to use `\u{2800}` and 4 spaces as opposed to 5 spaces?

Since the `Text` widget was getting rid of spaces at the time, I found this solution of using an invisible unicode character at the beginning so that spaces are not stripped from the beginning of the string.

But it was 3 years ago. Maybe there is another way of doing it now.

**Comment by ilyagr** [comment]
I see, thanks! I'll pay more attention to what happens at the beginning of strings.
