### ISSUE TITLE
Auto resizing causes a race condition

### ISSUE THREAD

**Issue by dotdash** [fdehau/tui-rs#99]
The auto-resizing implemented in #94 unfortunately makes it impossible to ensure that you're using the right size in your layout calculation.

Previously you'd use something like:
```rust
let new_size = terminal.size()?;
if size != new_size {
    size = new_size;
    terminal.resize(size)?;
}

terminal.draw(|mut f| { /* ... */ });
```
which ensures that the `size` variable later used to calculate the layout is the same size that is used for the buffer inside the `terminal` instance.

But now you have to do:
```rust
let size = terminal.size();
/* RACE WINDOW HERE */
terminal.draw(|mut f| { /* ... */ });
})
```

You have to ask for the size of the terminal first, and then, inside the draw() method, the size might change because of the automatic resizing. If the terminal is actually resized in between these two actions, the sizes get out of sync, and there's no way for the programmer to avoid the resulting artifacts or crash.

One way to handle this would be to adjust the callback in `draw()` to accept the current terminal size as a second parameter like this:

```rust
terminal.draw(|mut f, size| { /* ... */ });
```

That would ensure that the size matches the buffer size. If that sounds good to you, I could prepare a PR for that.

**Comment by dotdash** [comment]
cc @karolinepauls

**Comment by karolinepauls** [comment]
Another way is to turn Frame into a "rendering transaction object", with a consistent Terminal state snapshot as of render time. Then the "render-time consistent" size can be obtained from the Frame.
